packages/app/src/CreateLogAlertModal.tsx

fix typo in CreateLogAlertModal.tsx

---

.changeset/eight-cows-live.md
.vscode/settings.json
packages/api/src/models/alert.ts
packages/api/src/models/dashboard.ts
packages/api/src/routers/api/alerts.ts
packages/api/src/routers/api/dashboards.ts
packages/api/src/tasks/checkAlerts.ts
packages/app/src/DashboardPage.tsx
packages/app/src/types.ts
packages/app/styles/app.scss

* Add schemas and read path for Dashboard chart alerts
* Reuse existing `Alert` model
* Show a bell icon on dashboard chart tile if it has an alert associated

Chart alerts: add schemas and read path

---

.changeset/tall-lizards-care.md
packages/app/src/Alert.tsx
packages/app/src/CreateLogAlertModal.tsx
packages/app/src/types.ts

A small refactor in preparation for adding alert settings to charts.
Before – after:

Refactor: Extract shared alert logic into a separate component

---

.changeset/nice-steaks-perform.md
packages/api/src/clickhouse/index.ts
packages/api/src/clickhouse/searchQueryParser.ts
packages/api/src/controllers/alerts.ts
packages/api/src/fixtures.ts
packages/api/src/index.ts
packages/api/src/models/alert.ts
packages/api/src/routers/aggregator/root.ts
packages/api/src/routers/api/__tests__/dashboard.test.ts
packages/api/src/routers/api/__tests__/team.test.ts
packages/api/src/routers/api/alerts.ts
packages/api/src/routers/api/dashboards.ts
packages/api/src/routers/api/logs.ts
packages/api/src/routers/api/metrics.ts
packages/api/src/routers/api/sessions.ts
packages/api/src/server.ts
packages/api/src/tasks/checkAlerts.ts
packages/api/src/tasks/index.ts
packages/api/src/tasks/refreshPropertyTypeMappings.ts
packages/api/src/utils/__tests__/logParser.test.ts
packages/api/src/utils/__tests__/validators.test.ts
packages/api/src/utils/common.ts
packages/api/src/utils/logParser.ts
packages/api/tsconfig.json
packages/app/src/CreateLogAlertModal.tsx
packages/app/src/api.ts

Add support for chart alerts in alerts API

Chart alerts: Add support for chart alerts in alerts API

---

.changeset/gorgeous-meals-invent.md
.github/workflows/main.yml
docker/ingestor/Dockerfile

https://vector.dev/releases/0.34.0/

chore: bump vector to v0.34.0

---

.changeset/three-falcons-repair.md
packages/app/src/CreateLogAlertModal.tsx
packages/app/src/DashboardPage.tsx
packages/app/src/EditChartForm.tsx
packages/app/src/EditChartFormAlerts.tsx
packages/app/src/api.ts
packages/app/src/types.ts

Stacked on top of https://github.com/hyperdxio/hyperdx/pull/104
Actual commit: https://github.com/hyperdxio/hyperdx/pull/105/commits/b29369bf740b1e4a06b520dc1080a354acef41d2
Testing:

 Chart alert: Connect UI to API

---

.changeset/silly-balloons-happen.md
packages/app/src/EditChartForm.tsx
packages/app/src/EditChartFormAlerts.tsx

fix: Chart alert default interval

fix: Chart alert default interval

---

.changeset/bright-hornets-drop.md
packages/api/src/clickhouse/index.ts
packages/api/src/routers/api/logs.ts

fix regression from this pr https://github.com/hyperdxio/hyperdx/pull/104/files#diff-b32054de8cb6f383a1990dd7b7ee1b3cdf2c133a9ed46edcec5e44afcd4375bcL1643

fix: getLogBatchGroupedByBody missing return bug

---

.changeset/young-pans-search.md
packages/app/src/LogSidePanel.tsx
packages/app/src/LogSidePanelElements.tsx

- Show Trace tab for exceptions by default
- Add fetch and navigation info to breadcrumb columns

Log Side Panel: exceptions ui improvements

---

Makefile

Should remove all linked containers once test process exists

ci: int tests shutdown process (local)

---

.changeset/unlucky-timers-exercise.md
packages/app/src/HDXTableChart.tsx

Click on Table Tile to view all events
https://github.com/hyperdxio/hyperdx/assets/149748269/0386f9ad-e164-47da-927a-2b199250bc94

feat: Click on Table Tile to view all events

---

packages/app/src/AuthPage.tsx

fix: Auth page container width fix

---

.changeset/calm-keys-sneeze.md
packages/app/src/ChartUtils.tsx

feat: Loading and error states for metrics dropdown

---

.changeset/eighty-owls-nail.md
.vscode/settings.json
packages/api/src/models/dashboard.ts
packages/api/src/routers/api/dashboards.ts
packages/app/package.json
packages/app/pages/_app.tsx
packages/app/src/ChartUtils.tsx
packages/app/src/DashboardPage.tsx
packages/app/src/EditChartForm.tsx
packages/app/src/EditChartFormAlerts.tsx
packages/app/src/HDXLineChart.tsx
packages/app/src/HDXNumberChart.tsx
packages/app/src/HDXTableChart.tsx
packages/app/src/components/NumberFormat.tsx
packages/app/src/types.ts
packages/app/src/utils.tsx
yarn.lock

feat: Chart Number Formatting

---

.changeset/dirty-ads-exist.md
packages/app/src/ChartUtils.tsx
packages/app/src/HDXLineChart.tsx
packages/app/src/LogSidePanel.tsx
packages/app/src/config.ts

Under development ff for now to test it more thoroughly

feat: Log Side Panel Host Metrics

---

.changeset/famous-wasps-march.md
packages/app/src/DashboardPage.tsx

https://github.com/hyperdxio/hyperdx/assets/149748269/0b59fe63-3ec7-4e59-9fda-add5fcd309c8

feat: Show save badge in Dashboard Page

---

.changeset/flat-scissors-hang.md
packages/app/src/HDXLineChart.tsx
packages/app/styles/HDXLineChart.module.scss

feat: Line Chart - limit Legend items

---

.changeset/nasty-islands-shave.md
packages/app/src/HDXLineChart.tsx
packages/app/src/HDXMultiSeriesTimeChart.tsx
packages/app/styles/HDXLineChart.module.scss

Before:
After:
---
Before:
After:

feat: Update Line Chart tooltip styling

---

.changeset/eleven-peaches-scream.md
packages/api/src/tasks/checkAlerts.ts

fix: checkAlerts - add error handling

---

.changeset/great-knives-love.md
packages/app/src/AppNav.tsx

feat: display hyperdx version at the bottom of app nav bar

---

packages/app/src/ChartUtils.tsx
packages/app/src/EndpointLatencyTile.tsx
packages/app/src/HDXListBarChart.tsx
packages/app/src/HDXMultiSeriesTableChart.tsx
packages/app/src/HDXMultiSeriesTimeChart.tsx
packages/app/src/LogTableWithSidePanel.tsx
packages/app/src/ServiceDashboardPage.tsx
packages/app/src/types.ts
packages/app/src/useDisplayedColumns.ts

Service endpoint dashboard

---

.changeset/light-frogs-join.md
packages/app/src/AlertsPage.tsx
packages/app/src/AppNav.tsx

Add alerts to nav bar

---

.changeset/spicy-parents-count.md
packages/app/src/ServiceDashboardPage.tsx
packages/app/styles/app.scss

 feat: Add Pods table to Infra dashboard

---

packages/app/package.json
packages/app/src/HDXMultiSeriesTableChart.tsx
packages/app/src/LogTable.tsx
yarn.lock

there's a bad delay when switching tabs in infra dashboard. this pr should fix it

fix: Perf optimization for Table virtualization

---

packages/app/src/ChartUtils.tsx
packages/app/src/DashboardPage.tsx
packages/app/src/EditChartForm.tsx
packages/app/src/EndpointLatencyTile.tsx
packages/app/src/EndpointSidePanel.tsx
packages/app/src/HDXListBarChart.tsx
packages/app/src/HDXMultiSeriesTableChart.tsx
packages/app/src/HDXMultiSeriesTimeChart.tsx
packages/app/src/ServiceDashboardPage.tsx
packages/app/src/types.ts
packages/app/styles/app.scss

Still need to create the sidepanel component. Additionally found a bug(?) in our search query parser where we don't support double quotes in exact property searches, but figured I'd put that in a separate PR after some more testing + investigating if it's a breaking change.

Add db perf page

---

packages/app/src/PodDetailsSidePanel.tsx
packages/app/src/ServiceDashboardPage.tsx

feat: Add Infra Pod Side Panel

---

packages/app/src/ServiceDashboardPage.tsx

- Save active tab in url for infra dashboard
- Render only current tab

feat: Save active tab in url for infra dashboard

---

packages/app/src/PodDetailsSidePanel.tsx
packages/app/src/ServiceDashboardPage.tsx

fix: Adjusting K8s infra queries

---

packages/app/src/LogSidePanel.tsx
packages/app/src/PodDetailsSidePanel.tsx
packages/app/src/ServiceDashboardPage.tsx
packages/app/src/components/KubeComponents.tsx

* Add K8s Pod Timeline to Service Dashboard and Log Details metrics
* Minor styling tweaks

feat: Add K8s Pod Timeline to Service Dashboard and Log Details metrics

---

packages/api/src/clickhouse/index.ts
packages/app/src/DBQuerySidePanel.tsx
packages/app/src/EndpointSidePanel.tsx
packages/app/src/LogSidePanel.tsx
packages/app/src/ServiceDashboardPage.tsx
packages/app/src/types.ts

Adds a few new toggle options to the dashboard and swaps the http panel to be first

Service dashboard updates and fixes

---

packages/app/src/LogSidePanel.tsx
packages/app/src/PodDetailsSidePanel.tsx
packages/app/src/ServiceDashboardPage.tsx
packages/app/src/components/KubeComponents.tsx

Pod improvements and fixes

---

packages/app/src/LogSidePanel.tsx

fix: Rename Metrics tab to Infra

---

packages/app/src/DBQuerySidePanel.tsx
packages/app/src/EndpointLatencyTile.tsx
packages/app/src/EndpointSidePanel.tsx
packages/app/src/PodDetailsSidePanel.tsx
packages/app/src/ServiceDashboardPage.tsx
packages/app/src/components/DrawerUtils.tsx

* Close detail panes on esc
* Vertically align card title
* Fix pod metrics scroll

feat: Service Dashboard polish

---

packages/app/src/KubernetesDashboardPage.tsx
packages/app/src/ServiceDashboardPage.tsx
packages/app/src/components/KubeComponents.tsx

Mostly copypasta from Infrastructure dashboard

feat: Kubernetes Dashboard Pods

---

packages/app/src/KubernetesDashboardPage.tsx
packages/app/src/api.ts
packages/app/src/components/KubeComponents.tsx
packages/app/src/types.ts

feat: Pods table features

---

packages/api/src/routers/api/dashboards.ts
packages/app/pages/_app.tsx
packages/app/src/DashboardPage.tsx
packages/app/src/Tags.tsx
packages/app/styles/Tags.module.scss

https://github.com/hyperdxio/hyperdx/assets/149748269/c70572a6-78e1-47d0-aa3f-5310f34f30a1

feat: Allow to add tags to Dashboards

---

packages/app/src/ChartPage.tsx
packages/app/src/EditTileForm.tsx

Create dashboard from chart explorer

---

docker/ingestor/core.toml

Reverts hyperdxio/hyperdx#285
We need to handle the case when message body is json

Revert "feat: extract 'message' field in json body as _hdx_body"

---

packages/app/src/EditChartForm.tsx
packages/app/src/SearchTimeRangePicker.tsx

fix: Chart page time form fix

---

packages/app/src/DashboardPage.tsx
packages/app/src/EditChartForm.tsx
packages/app/src/EditTileForm.tsx

https://github.com/hyperdxio/hyperdx/assets/149748269/7e249228-90e9-4ad6-8004-08db2aff7035

feat: Better Dashboard filters UI

---

.changeset/fifty-pumpkins-film.md
packages/api/src/controllers/dashboard.ts
packages/api/src/routers/api/dashboards.ts
packages/api/src/routers/api/logViews.ts
packages/app/src/AppNav.tsx
packages/app/src/api.ts
packages/app/styles/AppNav.module.scss

https://github.com/hyperdxio/hyperdx/assets/149748269/15fb4bb0-db52-4a6c-b7c3-ac6357f04820

feat: Navbar Drag and Drop

---

packages/api/src/tasks/__tests__/checkAlerts.test.ts
packages/api/src/tasks/checkAlerts.ts

1. move `team` field out of default template view
2. fix `is_match` nested rendering issue
3. should render the template even if the channel type is specified

feat: alert template message pt5

---

.changeset/popular-llamas-change.md
packages/app/src/Playbar.tsx

Add skip forward/back 15s buttons on session replay

---

.changeset/rare-avocados-fry.md
package.json
packages/app/src/HDXMultiSeriesTableChart.tsx

Allow exporting table results as CSV

---

.changeset/plenty-jokes-end.md
packages/api/package.json
yarn.lock

https://github.com/ClickHouse/clickhouse-js/releases

chore: bump @clickhouse/client to v0.2.10

---

packages/api/src/models/teamInvite.ts

7 day invite expiration TTL

---

packages/api/src/models/teamInvite.ts
packages/app/src/TeamPage.tsx

lmk if copy needs adjustment 👍 
FIXES HDX-585

Invite Expiration: Change to 30day expiration + add copy

---

.changeset/stale-paws-confess.md
packages/app/src/TeamPage.tsx
packages/app/styles/TeamPage.module.scss

feat: Update TeamPage style

---

packages/app/src/DashboardPage.tsx
packages/app/src/HDXMultiSeriesTimeChart.tsx
packages/app/styles/app.scss

This reverts commit 14ae58b5afb6ae2a2d2dd553a942c9a8596773fe.

Revert "fix(Dashboard): Do not clip tooltips (#349)"

---

.changeset/wet-fireants-bathe.md
packages/app/src/components/HyperJson.tsx

https://github.com/hyperdxio/hyperdx/assets/20255948/c6ff3bb8-6df2-4be2-8c58-49a91b23429e

feat: Hide HyperJson buttons when selecting value

---

packages/app/.storybook/main.ts
packages/app/.storybook/preview-head.html
packages/app/.storybook/preview.tsx
packages/app/package.json
packages/app/pages/_app.tsx
packages/app/src/ThemeWrapper.tsx
packages/app/src/components/HyperJson.module.scss
packages/app/src/components/HyperJson.stories.tsx
packages/app/src/stories/Button.stories.tsx
yarn.lock

chore: Add Storybook 8

---

.changeset/shaggy-pants-fold.md
packages/api/src/tasks/__tests__/checkAlerts.test.ts
packages/api/src/tasks/checkAlerts.ts
packages/app/src/CreateLogAlertModal.tsx
packages/app/src/EditChartFormAlerts.tsx

fix: revisit `doesExceedThreshold` logic

---

.changeset/quiet-eagles-applaud.md
packages/app/src/LogSidePanelElements.stories.tsx
packages/app/src/LogSidePanelElements.tsx

feat: Use JSON viewer for Network Body

---

packages/app/src/ChartUtils.tsx
packages/app/src/EditChartForm.tsx
packages/app/src/HDXMultiSeriesTimeChart.tsx
packages/app/src/components/ColorSwatchInput.stories.tsx
packages/app/src/components/ColorSwatchInput.tsx
packages/app/src/types.ts

https://github.com/hyperdxio/hyperdx/assets/20255948/392b67b0-b5e3-4cc7-957d-6a95dd13532c
https://github.com/hyperdxio/hyperdx/assets/20255948/3e26ba3e-8c40-41fe-b457-502a802c7078

feat: Allow to customize line chart colors

---

.changeset/bright-countries-matter.md
.vscode/extensions.json
packages/app/pages/_app.tsx
packages/app/src/AutocompleteInput.tsx
packages/app/src/SearchPage.components.tsx
packages/app/src/SearchPage.stories.tsx
packages/app/src/SearchPage.tsx
packages/app/src/SearchTimeRangePicker.tsx
packages/app/src/__test__/searchFilters.test.ts
packages/app/src/searchFilters.tsx
packages/app/styles/SearchPage.module.scss

https://github.com/hyperdxio/hyperdx/assets/20255948/810fba03-c346-4543-91b7-8de2d7de191e

feat: Search Page Filters panel

---

.changeset/beige-hotels-deny.md
packages/app/src/SearchPage.components.tsx
packages/app/src/SearchPage.stories.tsx
packages/app/src/SearchPage.tsx
packages/app/src/components/ErrorBoundary.stories.tsx
packages/app/src/components/ErrorBoundary.tsx
packages/app/styles/SearchPage.module.scss

https://github.com/hyperdxio/hyperdx/assets/20255948/763f97f3-bf45-43cc-b5dd-b8e6f3ef6160
* Add ErrorBoundary
* Add ability to search filter values
* Show only first 5 filter values and allow the list to expand
* Update filter item "only" button styling to prevent the filter item from changing its height
* Update loading state styling

feat: Filter panel improvements

---

.changeset/brown-dryers-rest.md
packages/app/src/LogSidePanel.tsx

fix: Fix Search This Value button

---

.changeset/quick-pandas-vanish.md
packages/app/src/HDXListBarChart.tsx
packages/app/src/HDXMultiSeriesTableChart.stories.tsx
packages/app/src/HDXMultiSeriesTimeChart.tsx
packages/app/src/utils.tsx
packages/app/styles/HDXLineChart.module.scss
packages/app/styles/app.scss

feat: Deconflict Dashboard Chart Colors

---

.changeset/violet-pigs-decide.md
packages/app/src/KubernetesDashboardPage.tsx

feat: Add k8s cluster dropdown

---

.changeset/rare-adults-promise.md
packages/app/src/DSSelect.tsx
packages/app/src/DashboardPage.tsx
packages/app/src/GranularityPicker.tsx
packages/app/src/HDXMultiSeriesTimeChart.tsx
packages/app/src/api.ts
packages/app/src/hooks/useDashboardRefresh.tsx
packages/app/src/timeQuery.ts

https://github.com/hyperdxio/hyperdx/assets/20255948/efa47652-6c2a-4825-9141-ed651bbd86e8
* Refresh interval is equal to auto granularity value
* Do not allow to use custom granularity when live mode is active

feat: Dashboard auto-refresh

---

packages/app/src/JoinTeamPage.tsx
packages/app/src/TeamPage.tsx

- Removed extraneous components that aren't in v2 yet from team page
- Refactored out team member management to its own component for organization (+ minor style updates)
- Updated join team page to not be ugly legacy purple 😛

HDX-1246 Update and refactor team page for v2

---

packages/app/src/DBDashboardPage.tsx
packages/app/src/dashboard.ts

Dont try to save temp dashboards in server mode

---

packages/app/src/DBDashboardPage.tsx
packages/app/src/components/DBEditTimeChartForm.tsx
packages/app/src/components/DBRowTable.tsx
packages/app/src/components/SourceForm.tsx

Fix missing implicit column in dashboard tiles

---

packages/app/src/ClickhousePage.tsx

Adds additional function calls to ensure that the internal state of the timeranges is cleared appropriately.
Fixes HDX-1208

fix: Fix reset chart behavior on Clickhouse dashboard

---

.github/workflows/main.yml
docker-compose.ci.yml
packages/api/src/clickhouse/__tests__/clickhouse.test.ts
packages/api/src/clickhouse/__tests__/clickhouseGetMultiSeriesChart.test.ts
packages/api/src/clickhouse/__tests__/searchQueryParser.test.ts
packages/api/src/controllers/alerts.ts
packages/api/src/controllers/dashboard.ts
packages/api/src/controllers/team.ts
packages/api/src/fixtures.ts
packages/api/src/models/alert.ts
packages/api/src/models/logView.ts
packages/api/src/models/savedSearch.ts
packages/api/src/routers/api/__tests__/alerts.test.ts
packages/api/src/routers/api/__tests__/chart.test.ts
packages/api/src/routers/api/__tests__/dashboard.test.ts
packages/api/src/routers/api/__tests__/metrics.test.ts
packages/api/src/routers/api/__tests__/team.test.ts
packages/api/src/routers/api/alerts.ts
packages/api/src/routers/external-api/__tests__/alerts.test.ts
packages/api/src/routers/external-api/__tests__/charts.test.ts
packages/api/src/routers/external-api/__tests__/dashboard.test.ts
packages/api/src/routers/external-api/__tests__/v1.test.ts
packages/api/src/tasks/__tests__/checkAlerts.test.ts
packages/api/src/utils/commonTypes.ts
packages/api/src/utils/zod.ts

1. Enable CI integration tests
2. Migrate `logView` to `savedSearch` and `chartId` to `tileId` in alert model
3. Add more alert route tests

feat: enable alerts-part 1

---

.env
Makefile
docker-compose.ci.yml
docker-compose.dev.yml
docker-compose.yml
docker/fullstack/Dockerfile
docker/fullstack/entry.sh
docker/local/entry.sh
packages/api/src/api-app.ts
packages/api/src/clickhouse/index.ts
packages/api/src/config.ts
packages/api/src/fixtures.ts
packages/api/src/models/index.ts
packages/api/src/server.ts
packages/api/src/tasks/usageStats.ts
packages/api/src/utils/logger.ts
packages/api/src/utils/redis.ts
packages/app/package.json
packages/app/pages/api/[...all].ts

For better self-hosting experience, users should be able to run
```
docker run -e MONGO_URI=xxx -p 8080:8080 hyperdx/hyperdx:2-beta
```
to spin up the project that includes the server components

DX: standalone app docker image

---

packages/app/src/ChartUtils.tsx
packages/app/src/EditChartForm.tsx
packages/app/src/api.ts

fix: no need to show field dropdown for all 'count' agg functions

---

packages/app/src/components/SQLInlineEditor.tsx

Add some sql regular functions autocomplete support.
Ref: hdx-1086

feat: add more autocomplete support for sql regular functions

---

.github/workflows/release.yml
package.json
packages/api/.eslintignore
packages/api/.eslintrc.js
packages/api/migrate-mongo-config.ts
packages/api/tsconfig.json
packages/common-utils/.eslintignore
packages/common-utils/.eslintrc.js
packages/common-utils/jest.config.js
packages/common-utils/package.json
packages/common-utils/src/__tests__/queryParser.test.ts
packages/common-utils/src/clickhouse.ts
packages/common-utils/src/metadata.ts
packages/common-utils/src/queryParser.ts
packages/common-utils/src/renderChartConfig.ts
packages/common-utils/src/types.ts
packages/common-utils/src/utils.ts
packages/common-utils/tsconfig.json
packages/common-utils/tsup.config.ts
yarn.lock

- copy and paste the utils to a separate dir
- setup building + CD

feat: introduce common-utils package

---

.changeset/gorgeous-owls-lick.md
.github/workflows/release.yml
package.json
packages/common-utils/src/types.ts

@ernestii You should be able to import alert relates types from the `common-utils` after this PR

feat: add alert schema and types to common utils

---

packages/app/src/DBSearchPageAlertModal.tsx
packages/app/src/HDXMultiSeriesTimeChart.tsx
packages/app/src/components/AlertPreviewChart.tsx
packages/app/src/components/Alerts.tsx
packages/app/src/components/DBTimeChart.tsx

feat: Add chart preview to alert modal

---

packages/app/src/DBDashboardPage.tsx
packages/app/src/components/DBEditTimeChartForm.tsx
packages/app/src/dashboard.ts

noticed that there's no instant feedback when adding/editing a tile

feat: EditTileModal saving state

---

packages/api/src/tasks/__tests__/checkAlerts.test.ts
packages/api/src/tasks/checkAlerts.ts
packages/api/src/tasks/index.ts

feat: render sample logs in SavedSearch alert

---

packages/api/src/models/dashboard.ts
packages/api/src/routers/api/alerts.ts
packages/api/src/tasks/__tests__/checkAlerts.test.ts
packages/app/pages/alerts.tsx
packages/app/src/AlertsPage.tsx
packages/app/src/AppNav.tsx
packages/app/src/DBDashboardPage.tsx
packages/app/src/api.ts
packages/app/src/types.ts
packages/app/styles/AlertsPage.module.scss

feat: Alerts page

---

packages/api/src/tasks/checkAlerts.ts
packages/app/src/components/AlertPreviewChart.tsx

fix: implicit field rendering bug

---

packages/app/src/components/DBRowSidePanel.tsx
packages/app/src/components/DBRowTable.tsx
packages/app/src/hooks/useRowWhere.tsx
packages/common-utils/src/__tests__/clickhouse.test.ts
packages/common-utils/src/__tests__/queryParser.test.ts
packages/common-utils/src/clickhouse.ts
packages/common-utils/src/queryParser.ts

- search page can search/select json type data
- display page can display json type data
- one line search(display log detail) can display json data detail

Add JSON support

---

packages/app/src/AppNav.components.tsx
packages/app/src/AppNav.tsx

Just a little clean up to remove dead and duplicate code from AppNav component.

refactor: Reduce duplicate code in AppNav

---

.changeset/funny-dolls-explode.md
packages/api/src/models/source.ts
packages/api/src/tasks/__tests__/checkAlerts.test.ts
packages/app/src/components/OnboardingModal.tsx
packages/app/src/components/SourceForm.tsx
packages/app/src/config.ts
packages/common-utils/src/types.ts

feat: add session source and SourceKind enum

---

packages/app/src/DBSearchPage.tsx
packages/app/src/components/ContextSidePanel.tsx
packages/app/src/components/DBRowSidePanel.tsx

Adds surrounding context feature that allows users to visualize lines surrounding a selected line from search.
Ref: HDX-1250

feat: Add surrounding context pane from v1

---

packages/app/package.json
yarn.lock

chore: remove scss pkg

---

packages/app/src/AppNav.tsx

/dashboards is correct, also rename to Dashboards with an s.
Ref:HDX-1389

fix: Fix dashboard link in side nav

---

docker/otel-collector/config.yaml
package.json

1. add `CLICKHOUSE_USER` and `CLICKHOUSE_PASSWORD` env vars (clickhouse-exporter) - not used yet
2. disable debug exporter by default

style: cleanup otel-collector config

---

Makefile

Address https://github.com/hyperdxio/hyperdx/issues/483#issuecomment-2676841476
regression from this PR https://github.com/hyperdxio/hyperdx/pull/524

fix: build-local command

---

docker-compose.dev.yml
docker/clickhouse/local/config.xml
docker/otel-collector/config.yaml
packages/app/src/components/MetricNameSelect.tsx
packages/app/src/hooks/useMetadata.tsx

feat: scrape local otelcol + clickhouse metrics

---

packages/app/src/DBSearchPage.tsx
packages/app/src/components/DBRowDataPanel.tsx
packages/app/src/components/DBRowJsonViewer.tsx
packages/app/src/components/DBRowOverviewPanel.tsx
packages/app/src/components/DBRowSidePanel.tsx
packages/app/src/components/DBRowSidePanelHeader.tsx
packages/app/src/components/DBSearchPageFilters.tsx
packages/app/src/components/DBTracePanel.tsx
packages/app/src/components/EventTag.tsx
packages/app/src/components/HyperJson.module.scss
packages/app/src/components/NetworkPropertyPanel.tsx
packages/app/src/components/SQLInlineEditor.tsx
packages/app/src/components/SearchPageActionBar.tsx
packages/app/src/components/SelectControlled.tsx
packages/app/src/searchFilters.tsx
packages/app/src/timeQuery.ts
packages/app/src/utils/curlGenerator.ts

Clean overview panel, select input bug, saved search update, filter checkbox bug fix

---

.changeset/silent-dolphins-call.md
packages/api/src/clickhouse/__tests__/__snapshots__/renderChartConfig.test.ts.snap
packages/api/src/clickhouse/__tests__/renderChartConfig.test.ts
packages/common-utils/src/__tests__/__snapshots__/renderChartConfig.test.ts.snap
packages/common-utils/src/__tests__/renderChartConfig.test.ts
packages/common-utils/src/renderChartConfig.ts

Fix the sum query to produce the correct results from the min/max test case from v1.
Ref: HDX-1421

fix: update sum metric query based on v1 integration test

---

packages/app/src/components/DBRowDataPanel.tsx
packages/app/src/components/DBRowOverviewPanel.tsx
packages/app/src/components/DBSessionPanel.tsx
packages/app/src/components/ExceptionSubpanel.tsx

A lot of the components were v1 exception components I quickly migrated over - I suspect there's some ironing out some edge cases that might creep up but it seems to work fine.

Migrate exceptions subpanel to v2

---

.changeset/breezy-ligers-divide.md
packages/app/src/hooks/useChartConfig.tsx

1. Query multiseries charts
2. Readable chart name

feat: support multiseries metrics chart

---

packages/common-utils/src/metadata.ts

perf: introduce singleton __LOCAL_CACHE__

---

packages/api/src/clickhouse/__tests__/renderChartConfig.test.ts
packages/api/src/fixtures.ts
packages/api/src/tasks/__tests__/checkAlerts.test.ts
packages/common-utils/src/__tests__/__snapshots__/renderChartConfig.test.ts.snap
packages/common-utils/src/renderChartConfig.ts

fix: gauge metric attribute conflicts issue

---

packages/app/src/components/DBRowOverviewPanel.tsx

fix: stacktrace parsing issue

---

packages/app/src/DBSearchPage.tsx
packages/app/src/components/DBHeatmapChart.tsx
packages/app/src/components/DBRowTable.tsx
packages/app/src/hooks/useChartConfig.tsx
packages/app/src/hooks/useOffsetPaginatedQuery.tsx
packages/app/src/hooks/useRowWhere.tsx
packages/common-utils/src/clickhouse.ts
packages/common-utils/src/queryParser.ts
packages/common-utils/src/renderChartConfig.ts
packages/common-utils/src/types.ts

still not super smooth, but gets us most of the way there

add support for aliases in search, add WITH clause to chartconfig

---

packages/app/src/DBDashboardPage.tsx
packages/app/src/utils.ts

fix: metric type parsing issue

---

packages/api/src/tasks/checkAlerts.ts

- fix an issue where select query does not work correctly
ref: hdx-1476

Fix: slack alert empty body

---

.changeset/moody-chefs-juggle.md
packages/api/src/clickhouse/__tests__/renderChartConfig.test.ts
packages/common-utils/src/__tests__/__snapshots__/renderChartConfig.test.ts.snap
packages/common-utils/src/__tests__/renderChartConfig.test.ts
packages/common-utils/src/renderChartConfig.ts
packages/common-utils/src/types.ts

Some additional refactoring and testing around the more complex CTE rendering.
Ref: HDX-1511

refactor: clean up the chart config CTE render logic

---

packages/app/src/HDXMultiSeriesTableChart.tsx
packages/app/src/components/DBTableChart.tsx
packages/app/src/hooks/useOffsetPaginatedQuery.tsx
packages/app/src/utils.ts

Added FE logic to both limit query size of tables and a hook to monitor when a ref is scrolled into view
Ref: HDX-1500

fix: add limit of 200 + paginated query for table charts

---

.changeset/wise-wombats-hunt.md
packages/app/src/EditChartForm.tsx

feat: Allow to set table headers and chart line names

---

.changeset/sour-ravens-joke.md
packages/app/package.json
yarn.lock

https://github.com/advisories/GHSA-f82v-jwr5-mffw

chore: bump next to v13.5.10

---

.changeset/wet-owls-marry.md
packages/app/src/components/DBTimeChart.tsx
packages/common-utils/src/renderChartConfig.ts

Ref: HDX-1537
If no log source is associated with metric source, the app notifies users

fix:  metrics > logs correlation flow

---

packages/common-utils/src/__tests__/clickhouse.test.ts
packages/common-utils/src/clickhouse.ts

- Alias map will create correct map for bracket column
- Add unit test
Ref: hdx-1535

fix: incorrect alias map for bracket column

---

.changeset/honest-steaks-allow.md
packages/app/src/DBSearchPage.tsx

https://github.com/user-attachments/assets/9f0542fa-af9d-4b39-9421-26a8e512e693
Ref: HDX-1479

fix: don't show ellipses on search when query is in-flight

---

packages/app/src/components/DBRowOverviewPanel.tsx
packages/app/src/components/DBRowSidePanel.tsx
packages/app/src/components/DBSearchPageFilters.tsx

hide duplicate side panel overview header component

---

packages/app/src/components/SourceForm.tsx

feat: add optional correlated metric source to TraceTableModelForm

---

.changeset/nervous-steaks-bathe.md
packages/common-utils/src/__tests__/metadata.test.ts
packages/common-utils/src/metadata.ts

Ref: HDX-1566
pull the fix from PR https://github.com/hyperdxio/hyperdx/pull/718

fix: transform `partition_key` to be the same format as others

---

packages/app/src/DBSearchPage.tsx
packages/app/src/components/DBRowSidePanel.tsx
packages/app/src/components/DBSearchPageFilters.tsx
packages/app/src/hooks/__tests__/useResizable.test.tsx
packages/app/src/hooks/useResizable.tsx
packages/app/src/hooks/useResizeable.tsx
packages/app/styles/ResizablePanel.module.scss
packages/app/styles/SearchPage.module.scss

* Extracts resize logic into a reusable hook
* Adds a test suite for said hook
* Replace resize logic for DBRowSidePanel with the hook
* Implement hook for use in DBSearchFilters
* Profit
Ref: HDX-1564

feat: Allow for filter pane to be resizable

---

packages/app/src/HDXMultiSeriesTimeChart.tsx

fix: z-index goldilocks zone

---

packages/app/src/DBSearchPage.tsx

Fixes an issue where filter values carried over when data sources changed. This could cause errors when there are columns not available in said source.
[screen-capture (8).webm](https://github.com/user-attachments/assets/65a41333-fd68-49fa-9791-8a20e9bcb9bf)
Ref: HDX-1458

fix: Clear search filters when data source is changed

---

packages/app/src/AutocompleteInput.tsx

Closes: #741
[Screencast from 2025-04-08 21-33-30.webm](https://github.com/user-attachments/assets/e70f29d0-bfde-45e9-8eaf-34e4027bfc76)

minor-fix: UI-metrics search overflow

---

packages/app/src/components/DBEditTimeChartForm.tsx
packages/app/src/components/MetricNameSelect.tsx

fix: setup date range boundary for `MetricNameSelect` comp

---

.changeset/five-glasses-live.md
packages/app/src/components/DBEditTimeChartForm.tsx
packages/common-utils/src/metadata.ts

fix: add optional metric name filtering to useAllFields

---

.changeset/forty-hounds-grin.md
packages/app/src/BenchmarkPage.tsx
packages/app/src/sessions.ts
packages/common-utils/src/clickhouse.ts

Still uses the old fetch method on local mode
Ref: HDX-1630
Ref: HDX-1653

feat: use clickhouse client lib by default for queries

---

.github/workflows/main.yml

Added an another job the CI build definitions to run the smoke tests for the OTEL collector configuration.
Ref: HDX-1642

build: added OTEL smoke tests to CI

---

packages/app/src/DBSearchPage.tsx
packages/app/src/components/PatternSidePanel.tsx
packages/app/src/components/PatternTable.tsx
packages/app/src/hooks/usePatterns.tsx

- Add a details panel with sample events to the patterns table
- Log side panel for sample events

feat: Pattern side panel

---

packages/app/src/components/DBEditTimeChartForm.tsx

Fixes this flow:
- create new dashboard
- create new search tile
- save
- attempt to edit that tile
- hit preview

fix: Fix Search tile preview when editing

---

packages/api/src/controllers/team.ts
packages/api/src/routers/api/__tests__/team.test.ts
packages/api/src/routers/api/team.ts
packages/app/src/TeamPage.tsx
packages/app/src/api.ts

feat: rename team and rotate api key

---

packages/app/src/components/DBRowDataPanel.tsx
packages/app/src/components/DBRowOverviewPanel.tsx
packages/app/src/components/SpanEventsSubpanel.tsx

feat: show span events in overview tab

---

docker-compose.yml

feat: comment out db and clickhouse ports with security warning

---

packages/app/src/components/MetricNameSelect.tsx

This reverts commit b6324d757145e54d998ee79e2393d5dfdb5570d2.

Revert "temp disable histogram metric select (#735)"

---

packages/app/src/sessions.ts

fix: session search where doesnt get applied consistently

---

.changeset/smooth-suns-shop.md
packages/app/src/TeamPage.tsx
packages/app/src/components/DBRowSidePanel.tsx
packages/app/src/components/DBSessionPanel.tsx

fix: session panel display state

---

.changeset/short-rockets-behave.md
packages/app/src/DOMPlayer.tsx

fix: Session replay intermittently showing No replay available for this session

---

.changeset/dirty-carrots-peel.md
packages/app/src/components/DBEditTimeChartForm.tsx

fix: chartpage querying too on every keystroke after initial query

---

packages/app/src/components/OnboardingModal.tsx

chore: update demo instance

---

.changeset/gold-owls-hug.md
docker/hyperdx/Dockerfile
docker/hyperdx/entry.local.base.sh
docker/hyperdx/entry.prod.sh

aio: 3GB -> 2.2GB
app: 2.05GB -> 1.27GB
Ref: HDX-1803

perf: merge api + app packages to dedupe node_modules

---

.changeset/gorgeous-feet-search.md
docker/hyperdx/Dockerfile
packages/api/src/middleware/error.ts
packages/api/src/opamp/controllers/opampController.ts
packages/app/Dockerfile

bonus adjust logging (otel config + exception)

fix: missing types in app build

---

packages/common-utils/src/types.ts

fix: dashboard names should be required to have minimum 1 character

---

.changeset/tender-mails-punch.md
packages/app/src/components/ConnectionForm.tsx
packages/app/src/components/__tests__/ConnectionForm.test.tsx
packages/app/src/connection.ts

refactor: remove duplicate `Connection` type definition

---

.changeset/silver-feet-design.md
packages/api/src/controllers/team.ts
packages/api/src/models/team.ts
packages/api/src/routers/api/team.ts
packages/app/src/DBDashboardPage.tsx
packages/app/src/DBSearchPage.tsx
packages/app/src/TeamPage.tsx
packages/app/src/api.ts
packages/app/src/components/DBRowTable.tsx
packages/app/src/config.ts
packages/app/src/defaults.ts

feat: configurable search row limit

---

.changeset/itchy-stingrays-learn.md
packages/app/src/ChartUtils.tsx
packages/app/src/components/DBEditTimeChartForm.tsx
packages/common-utils/src/renderChartConfig.ts
packages/common-utils/src/types.ts

feat: Add any aggFn support, fix select field input not showing up

---

packages/common-utils/src/clickhouse.ts

fix: add delete case for both authorization spellings

---

.changeset/sweet-pigs-check.md
packages/app/src/hooks/useAutoCompleteOptions.tsx

Fixes HDX-2185
Credit to @MikeShi42

fix: Date.now() called causing crazy rerenders

---

.changeset/cyan-camels-check.md
packages/app/src/DBDashboardPage.tsx

- Fix issue https://github.com/hyperdxio/hyperdx/issues/1025
Users can now update the chart type on their dashboard

chore: show display switcher on dashboard page

---

.changeset/lemon-pans-play.md
packages/app/src/DBSearchPage.tsx
packages/app/src/__tests__/DBSearchPage.test.tsx

feat: support toUnixTimestamp style timestamps in ORDER BY

---

.github/workflows/release-nightly.yml
Makefile

The nightly build are being skipped currently

fix: should not check tag for nightly builds

---

.changeset/violet-bats-invent.md
packages/app/src/components/DBTableChart.tsx

Closes HDX-2272
Fixes #1108
This fixes the linked issue

fix: format number for queried column, not group by columns

---

packages/common-utils/src/metadata.ts

fix: json filters regression

---

.changeset/rotten-trains-burn.md
packages/app/src/AppNav.components.tsx

https://linear.app/clickhouse/issue/HDX-1800/emailname-text-overflows-app-nav

fix text overflowing issue in app nav user menu

---

packages/app/src/components/OnboardingModal.tsx

Add ClickPy demo source

---

packages/app/src/AppNav.tsx
packages/app/src/KubernetesDashboardPage.tsx
packages/app/src/NamespaceDetailsSidePanel.tsx
packages/app/src/NodeDetailsSidePanel.tsx
packages/app/src/PodDetailsSidePanel.tsx
packages/app/src/components/KubernetesFilters.tsx
packages/app/tests/e2e/features/kubernetes.spec.ts

Closes HDX-2449
This PR adds e2e tests for the preset k8s dashboard.

test: Add E2E tests for k8s dashboard

---

.changeset/young-tools-sneeze.md
packages/app/src/components/DBRowJsonViewer.tsx
packages/app/src/components/HyperJson.tsx
packages/app/tests/e2e/features/traces-workflow.spec.ts

feat: Add support for filter by parsed JSON string
