hyperdxio/hyperdx

.changeset/thick-rings-peel.md, .kodiak.toml, README.md, docker/clickhouse/local/users.xml, packages/api/src/clickhouse/index.ts
The ultimate goal is to remove the clickhouse config mounting at `docker-compose.yml` so people can spin up the project w/o copying `docker/clickhouse` dir
=> refactor: set output datetime format on the client side

docker/ingestor/Dockerfile
Not in this PR. We might need to migrate vector config files from TOML -> YAML (https://vector.dev/highlights/2023-08-30-yaml-default-format/)
=> chore: bump vector base image to v0.33.0

docker-compose.ci.yml, docker-compose.dev.yml, docker-compose.yml
for docker-vompose v1x, it throws error like:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.ingestor.environment.VECTOR_OPENSSL_LEGACY_PROVIDER contains false, which is an invalid type, it should be a string, number, or a null
```
=> fix: boolean env var type issue (older compose version)

.changeset/five-melons-grin.md, packages/app/global-setup.js, packages/app/jest.config.js, packages/app/package.json, packages/app/src/DashboardPage.tsx, packages/app/src/__test__/fixtures.ts, packages/app/src/__test__/timeQuery.test.tsx, packages/app/src/timeQuery.ts, yarn.lock
This PR relates to https://github.com/hyperdxio/hyperdx/issues/53. From a chat with @MikeShi42 a while back we were discussing the UX of the time query presets (e.g. "Past 1h") and how it's kind of confusing atm. Once you click a preset, the label will remain as "Past 1h" and add a `from` and `to` param to the url. If after some time you refresh the page, the label will still say "Past 1h" but the `from` and `to` are the old values. At the same time, the existing useTimeQuery hook has a ton of complex logic which makes it very tricky to modify without causing regressions.
Create a new version of the useTimeQuery hook (temporarily calling it useNewTimeQuery) and add detailed unit testing to it for all the different cases. This can eventually be used to replace all the existing callsites of …
=> Add new useTimeQuery hook

.changeset/empty-ears-kneel.md, packages/api/src/clickhouse/index.ts, packages/app/src/ChartPage.tsx, packages/app/src/ChartUtils.tsx, packages/app/src/Checkbox.tsx, packages/app/src/EditChartForm.tsx, packages/app/src/api.ts
Found a few things that we'd likely need to clean up for https://github.com/hyperdxio/hyperdx/issues/76, but I think this makes a huge improvement in making sum metrics usable.
=> Add rate aggFn support for sum metrics

.changeset/poor-chefs-glow.md, packages/api/src/routers/api/__tests__/team.test.ts, packages/api/src/routers/api/root.ts, packages/app/src/AuthPage.tsx, packages/app/src/api.ts
Origin: https://github.com/hyperdxio/hyperdx/pull/81#discussion_r1384379205
Add a password confirmation field to the registration form.
- API will require `confirmPassword` field on the registration endpoint
- The `confirmPassword` and `password` fields will be validated by zod on API validation
- UI on the registration form will have a "Confirm Password" field
- Validation errors will be displayed on the UI the same way other validation errors
- API test covers mismatch between `confirmPassword` and `password` (simple check, can be improved)
=> feat(register): password confirmation

.changeset/healthy-drinks-lie.md, packages/app/src/LogSidePanel.tsx, packages/app/src/LogSidePanelKbdShortcuts.tsx, packages/app/src/LogTable.tsx, packages/app/src/config.ts, packages/app/styles/LogSidePanel.module.scss, packages/app/styles/LogTable.module.scss, packages/app/styles/app.scss, packages/app/styles/variables.scss
* Tweak colors and contrast for log table row hover and selected state
* Styling tweaks for LogSidePanel – header, shadow, borders, etc
* Add [X] button to LogSidePanel
* Use CSS modules for styling
* LogTable – use chevron icon instead of `>` symbol
* Use `col-resize` cursor when resizing LogTable columns
* Use correct env var for HDX_API_KEY in `app` to fix client sessions
=> LogTable and LogSidePanel UI tweaks

.changeset/light-zoos-add.md, packages/api/src/routers/api/__tests__/team.test.ts, packages/api/src/routers/api/team.ts, packages/app/pages/_app.tsx, packages/app/src/TeamPage.tsx
=> Add Sentry integration info

.changeset/slimy-bananas-juggle.md, packages/app/src/DashboardPage.tsx, packages/app/styles/app.scss
Pulse effect:
https://github.com/hyperdxio/hyperdx/assets/149748269/2908f086-4349-4cd1-839f-3921ed0391d2
=> feat(Chart Alerts): Show alert state

.changeset/angry-goats-notice.md, .changeset/cool-ads-fail.md, CONTRIBUTING.md, packages/app/.eslintrc.js, packages/app/.storybook/main.ts, packages/app/.storybook/preview.ts, packages/app/package.json, packages/app/pages/_app.tsx, packages/app/src/LogSidePanel.tsx, packages/app/src/LogSidePanelElements.tsx, packages/app/src/components/Table.module.scss, packages/app/src/components/Table.tsx, packages/app/src/stories/.eslintrc.js, packages/app/src/stories/LogSidePanelElements.mocks.ts, packages/app/src/stories/LogSidePanelElements.stories.tsx, packages/app/src/stories/Logo.stories.tsx, packages/app/src/stories/components/Table.stories.tsx, packages/app/src/types.ts, packages/app/styles/app.scss, packages/app/tsconfig.json, packages/app/tsconfig.storybook.json, yarn.lock
**Sentry exceptions ui improvements**
* Show data for XHR (method, status, url)
* Show http status and console.log level in the `category` column for better visibility
* Show only 5 most recent frames and breadcrumbs with a button to show all rows
* Better text truncating
https://github.com/hyperdxio/hyperdx/assets/149748269/c43c9acf-1c2c-4725-97ea-2c49b7ab2263
=> Sentry exceptions ui improvements

packages/app/src/TeamPage.tsx
Some people offer a slack-compatible webhook that is not hosted on the Slack domain, this removes the domain check to allow people to enter any URL they like
=> Remove validation for slack-specific URL in webhook configuration

.changeset/healthy-elephants-give.md, packages/app/src/Alert.tsx, packages/app/src/EditChartForm.tsx, packages/app/src/TeamPage.tsx, packages/app/src/config.ts
* Allow to set alerts for metric charts on development env
* Validation improvements for webhook alerts form (HDX-213)
=> feat: Enable metric alerts on dev

.changeset/fifty-papayas-look.md, docker-compose.dev.yml, packages/api/package.json, packages/api/src/api-app.ts, packages/api/src/config.ts, packages/app/src/LogSidePanel.tsx, yarn.lock
Sentry DSN config is mainly for us to test against our own ingestor. In case anyone runs across this you need to set SENTRY_DSN to `http://YOUR_KEY_WITHOUT_DASHES@ingestor:8002/0` (you need to use `ingestor`, not `localhost` as the api server won't resolve that to the ingestor)
=> fix: Sentry exception in the side panel should not assume all events in trace are exceptions, add Sentry SDK to API server

.changeset/mighty-pumas-fry.md, packages/app/src/LogSidePanel.tsx
=> feat: Add K8s event tags

.changeset/lemon-ads-collect.md, packages/app/src/AlertsPage.tsx, packages/app/src/DashboardPage.tsx, packages/app/src/SearchPage.tsx, packages/app/styles/AlertsPage.module.scss, packages/app/styles/app.scss
=> feat: Alerts page styling

.changeset/eighty-cows-leave.md, packages/api/src/clickhouse/index.ts, packages/api/src/config.ts, packages/api/src/fixtures.ts, packages/api/src/routers/api/__tests__/alerts.test.ts, packages/api/src/routers/api/__tests__/dashboard.test.ts, packages/api/src/routers/api/__tests__/metrics.test.ts, packages/api/src/routers/api/metrics.ts, packages/api/src/routers/external-api/__tests__/v1.test.ts, packages/api/src/routers/external-api/v1/index.ts, packages/api/src/utils/redis.ts
1. introduce a caching abstraction SimpleCache
2. add time range filtering to getMetricsTags query
=> perf + feat: introduce SimpleCache and specify getMetricsTags time range

.changeset/stale-nails-juggle.md, packages/app/src/HDXLineChart.tsx, packages/app/styles/HDXLineChart.module.scss
https://github.com/hyperdxio/hyperdx/assets/149748269/3e61efec-39bd-4dc9-b0b8-b044490f405c
=> feat: Use Popover instead of Tooltip for line chart overflow

packages/app/src/HDXMultiSeriesTimeChart.tsx
We were showing the "Only showing top N groups" indicator in line charts extraneously from #184. I've removed the UI since it's been somewhat broken for some while, and patched the group counter logic so it's not completely broken at least.
=> Fix time chart group count regression

packages/app/src/ServiceDashboardPage.tsx
extract `_searchQuery` and search input into a separate component to prevent re-rendering the entire page dom
=> fix: Service Dashboard input perf

.changeset/violet-singers-melt.md, packages/api/src/routers/api/__tests__/chart.test.ts, packages/api/src/routers/api/chart.ts
The bug happened when:
1. Property map has custom attributes
2. Found log lines don't have custom properties
And because the query has 'group-by' column checks in where clause, it ends up no matches
even 'service' should exist.
=> fix: services endpoint bug

.changeset/pink-waves-yell.md, packages/app/src/AppNav.tsx, packages/app/src/DashboardPage.tsx, packages/app/src/api.ts, packages/app/src/types.ts, packages/app/styles/AppNav.module.scss
https://github.com/hyperdxio/hyperdx/assets/149748269/a40d38fa-09a6-4d50-9e15-b9d066af4b34
**Upd:**
| Loading | Empty | Not found |
|--------|--------|--------|
| ![Screenshot 2024-01-13 at 11 54 41 AM](https://github.com/hyperdxio/hyperdx/assets/149748269/73162f59-e2b9-4b1e-9bf5-28dfb81d9826) | ![Screenshot 2024-01-13 at 12 17 09 PM](https://github.com/hyperdxio/hyperdx/assets/149748269/deab0b79-6a54-4203-850d-bba822353b50)  | ![Screenshot 2024-01-13 at 11 56 16 AM](https://github.com/hyperdxio/hyperdx/assets/149748269/e7175598-537f-44ec-852d-4450b9ff22a0) |
=> feat: AppNav improvements

packages/app/pages/_app.tsx, packages/app/src/AlertsPage.tsx, packages/app/src/AppNav.tsx, packages/app/src/ChartPage.tsx, packages/app/src/DashboardPage.tsx, packages/app/src/SearchPage.tsx, packages/app/src/ServiceDashboardPage.tsx, packages/app/src/SessionsPage.tsx, packages/app/src/TeamPage.tsx, packages/app/src/layout.tsx, packages/app/styles/AppNav.module.scss
Before
https://github.com/hyperdxio/hyperdx/assets/149748269/9974cb6e-acc5-4790-8878-d3fdfeba937c
---
After:
https://github.com/hyperdxio/hyperdx/assets/149748269/5c86a4b1-17f0-4b10-915c-219d01dd3c68
=> feat: Persist AppNav between navigations

packages/app/src/KubernetesDashboardPage.tsx, packages/app/src/utils.tsx
=> feat: Node page

packages/api/src/routers/api/logViews.ts, packages/app/src/DashboardPage.tsx, packages/app/src/SearchPage.tsx, packages/app/src/Tags.tsx, packages/app/src/api.ts, packages/app/src/types.ts
feat: Allow to add tags for saved searches
=>  feat: Allow to add tags for saved searches

packages/app/src/AutocompleteInput.tsx, packages/app/src/ChartUtils.tsx, packages/app/src/HDXMultiSeriesTimeChart.tsx, packages/app/src/SearchInput.tsx
- Disable metric line chart if series is missing metric name
- Allow where field autocomplete to show up properly with zindex
- One click toggle between metrics and logs/spans data source
- Draw dots for line charts if the series is non-continuous (UX duct tape for discontinuous series for now)
=> Fix UI rough edges on charts

.changeset/thin-toes-smile.md, packages/api/src/routers/api/chart.ts, packages/api/src/routers/api/metrics.ts, packages/api/src/routers/external-api/v1/index.ts, packages/api/src/utils/redis.ts
In most of cases, we don't want to cache the result if its empty (because the data hasnt been ingested yet)
=> fix: cache the result conditionally (SimpleCache)

.changeset/lazy-terms-taste.md, packages/app/src/ChartPage.tsx, packages/app/src/ChartUtils.tsx, packages/app/src/DashboardPage.tsx, packages/app/src/EditChartForm.tsx, packages/app/src/EditTileForm.tsx, packages/app/src/HDXMultiSeriesTableChart.tsx, packages/app/src/HDXMultiSeriesTimeChart.tsx
=> Unify chart page to use edit chart form in dashboard

.changeset/warm-berries-wash.md, packages/api/src/clickhouse/index.ts, packages/api/src/routers/api/__tests__/metrics.test.ts, packages/api/src/routers/api/metrics.ts, packages/api/src/routers/external-api/__tests__/v1.test.ts, packages/api/src/routers/external-api/v1/index.ts, packages/app/src/ChartUtils.tsx, packages/app/src/MetricTagFilterInput.tsx, packages/app/src/MetricTagValueSelect.tsx, packages/app/src/api.ts, packages/app/src/types.ts, packages/app/src/utils.tsx
1. endpoints to fetch metrics names and tags separately
2. performance improvement (use _created_at partition filtering)
=> refactor: metrics tags endpoints

packages/api/src/clickhouse/__tests__/clickhouse.test.ts, packages/api/src/clickhouse/index.ts
Previously, we'd only join on the first series groupby values, which can lead to groups being dropped if it didn't exist in series_0. This will allow groups from all series to be included in the final result.
We still need to make some improvements to the 0 fill and `join_use_nulls` (and let the user opt in to whether they want to get null values back or 0 values back when values are missing)
=> Join on all keys in multi series chart

.changeset/soft-bananas-clean.md, packages/app/src/AppNav.tsx, packages/app/src/DashboardPage.tsx, packages/app/src/SearchPage.tsx, packages/app/src/Tags.tsx, packages/app/styles/AppNav.module.scss
**Minor tweaks and fixes:**
* [AppNav] Use `ScrollArea` component to re-style scrollbars for consistency across platforms
* [AppNav] Show search inputs even if there's less than 1 saved search/dashboard (for styling and for better CMD+K discoverability)
* [AppNav] Tweak text and icon colors
* [Search Page] Add spacing between icon and text in "Zoom Out", "Zoom In" btns
* [Search Page] Fix Tags count text appearing on top of Details panel
* [Tags Popup] Open by clicking instead of by hover for 1) better ux 2) better accessibility
* [Tags Popup] Sort tags alphabetically, otherwise they rearrange constantly while using
* [Tags Popup] Align tags popup to bottom-left so it doesn't reposition when parent element changes size (like when adding filters in Alerts page)
* [Dashboard Page] Use …
=> Minor UI fixes

packages/api/src/tasks/__tests__/checkAlerts.test.ts, packages/api/src/tasks/checkAlerts.ts
1. update `dashboard` and `savedSearch` external schema mappings
2. prepare for the template engine
=> feat: alert template message - pt2

.vscode/extensions.json, .vscode/settings.json, packages/app/package.json, packages/app/pages/_app.tsx, packages/app/postcss.config.cjs, packages/app/src/AlertsPage.tsx, packages/app/src/AppNav.tsx, packages/app/src/AuthPage.tsx, packages/app/src/DashboardPage.tsx, packages/app/src/HDXListBarChart.tsx, packages/app/src/KubernetesDashboardPage.tsx, packages/app/src/LogSidePanel.tsx, packages/app/src/NamespaceDetailsSidePanel.tsx, packages/app/src/NodeDetailsSidePanel.tsx, packages/app/src/ServiceDashboardPage.tsx, packages/app/src/Spotlights.tsx, packages/app/src/Tags.tsx, packages/app/src/components/DrawerUtils.tsx, packages/app/src/components/KubeComponents.tsx, packages/app/src/components/NumberFormat.tsx, packages/app/styles/AppNav.module.scss, packages/app/styles/app.scss, yarn.lock
really like the fact they moved away from css-in-js haha
```
Stack/Group spacing => gap
Stack/Group position => justify
Button compact prop => size
Button, Input, etc icon/leftIcon prop => leftSection
sx prop => style
Table thead/tbody/tr/td => <Table.Thead> / <Table.Tbody> / <Table.Tr> / <Table.Td>
Badge - set variant="light" prop
```
To do:
more testing won't hurt :D
=> chore: Upgrade to Mantine@7

packages/app/src/HDXListBarChart.tsx
=> fix: Fix empty state for HDXSpanPerformanceBarChart

packages/api/src/tasks/__tests__/checkAlerts.test.ts, packages/api/src/tasks/checkAlerts.ts
users should be able to use the same path expression (with `.`) for all template helpers or within handlebar
=> feat: alert template message pt6

docker-compose.dev.yml, docker-compose.yml, packages/api/src/controllers/alerts.ts, packages/api/src/models/alert.ts, packages/api/src/routers/api/alerts.ts, packages/api/src/routers/api/root.ts, packages/api/src/tasks/checkAlerts.ts, packages/app/src/AlertsPage.tsx, packages/app/src/DashboardPage.tsx, packages/app/src/api.ts, packages/app/src/types.ts, packages/app/styles/AlertsPage.module.scss, packages/app/styles/app.scss
=> feat: Acknowledge and Silence Alerts

.changeset/gentle-rats-suffer.md, packages/api/src/clickhouse/index.ts
If the user turns of user interaction instrumentation, or the session has no interactions, we should still show the session in the sessions page as long as we believe there's an associated recording.
=> Show client sessions with no user interactions in sessions results page

README.md, docker-compose.dev.yml, docker-compose.yml, docker/local/Dockerfile, docker/local/README.md, docker/local/clickhouseConfig.xml, docker/local/entry.sh, packages/app/pages/_app.tsx, packages/app/pages/api/config.ts, packages/app/src/AppNav.tsx, packages/app/src/AuthPage.tsx, packages/app/src/JoinTeamPage.tsx, packages/app/src/LogTable.tsx, packages/app/src/PasswordResetPage.tsx, packages/app/src/PatternTable.tsx, packages/app/src/api.ts, packages/app/src/config.ts, packages/app/src/iacUtils.tsx, packages/app/src/search.ts
Makes a number of improvements to local mode:
- Allows for custom port overwrites
- Hides irrelevant UI such as logout and log patterns in local mode
- Improve docs
General changes:
- Fix `NEXT_PUBLIC_SERVER_URL` typo in docker-compose (and standardize constant name exported from config)
- Make log patterns button more visible and more intuitive wording
- Allows for dynamic API server overrides without rebuilding the frontend (fixes https://github.com/hyperdxio/hyperdx/issues/12), though probably need some documentation.
=> Improve local mode

packages/api/package.json, packages/api/src/controllers/team.ts, packages/api/src/routers/api/__tests__/team.test.ts, packages/api/src/routers/api/team.ts, packages/app/src/CreateLogAlertModal.tsx, packages/app/src/TeamPage.tsx, packages/app/src/api.ts, yarn.lock
The `/team` endpoint should only fetch team metadata instead of pulling both members and invites
=> perf: decouple team member + invitation services

.changeset/grumpy-tools-sin.md, packages/app/src/LogSidePanel.tsx, packages/app/src/components/HyperJson.tsx
* actually parse JSON to check if JSON is valid
* wrap lines by default
=> fix: Log viewer json viewer fixes

packages/app/src/DashboardPage.tsx, packages/app/src/HDXMultiSeriesTimeChart.tsx, packages/app/styles/app.scss
https://github.com/hyperdxio/hyperdx/assets/149748269/cfda74ae-f7cf-4f96-a0cb-2bd033ec5461
=> fix(Dashboard): Do not clip tooltips

.changeset/sweet-icons-boil.md, docker/ingestor/core.toml
=> perf: remove redundant otel-logs fields (`timestamp` + `spanID` + `traceID`)

packages/app/pages/_app.tsx, packages/app/src/Spotlights.tsx
Translating app with Chrome Translate breaks react renders and causes the page to crash:
https://github.com/facebook/react/issues/11538
=> fix: Disallow usage of translation in app

.changeset/shy-doors-matter.md, packages/app/src/AlertsPage.tsx, packages/app/src/AppNav.tsx, packages/app/src/HDXMultiSeriesTimeChart.tsx, packages/app/src/LogSidePanel.tsx, packages/app/src/LogSidePanelElements.tsx, packages/app/src/LogTable.tsx, packages/app/src/Playbar.tsx, packages/app/src/PlaybarSlider.tsx, packages/app/src/SearchPage.tsx, packages/app/src/SessionSubpanel.tsx, packages/app/src/SessionsPage.tsx, packages/app/src/UserPreferencesModal.tsx, packages/app/src/__test__/utils.test.ts, packages/app/src/components/KubeComponents.tsx, packages/app/src/timeQuery.ts, packages/app/src/useFormatTime.tsx, packages/app/src/utils.tsx
To do:
Keeping as is (they handle isUTC but they don't need am/pm config):
=> refactor: Update usage of date formatting

.changeset/dull-countries-fold.md, packages/app/src/SearchPage.components.tsx, packages/app/src/SearchPage.stories.tsx
* Add an empty state for filter options
* Show selected services even when the list is collapsed
* Increase max filter size to `10`
=> feat: Filter panel improvements

.changeset/honest-ears-allow.md, docker-compose.ci.yml, packages/api/src/aggregator-app.ts, packages/api/src/utils/errors.ts
500 errors will cause ingestors to slow down due to ARC (https://vector.dev/docs/reference/configuration/sinks/http/#request.adaptive_concurrency), which is good.
However, for case like 413 (due to aggregator payload size limit), ingestors shouldn't slow down and be blocked.
The fix here is to return the original status code so ARC will tune up the concurrency properly
Before:
Events buffer will be queued up and ingestors will be blocked (concurrency stays)
Now:
Events buffer will be cleared out properly (concurrency increases) 
TODO: we want to revisit the error global handler to make sure the proper status code is returned
=> fix: aggregator should return 413 (Content Too Large) to make ingestor ARC work properly

.changeset/wild-chairs-compare.md, packages/app/src/DashboardPage.tsx
Test plan:
- Go to preset dashboard
- Try add a new tile, hit save
- It should add the new tile
- Save dashboard
- It should create a new saved dashboard
=> fix: Allow to edit preset dashboards

packages/api/src/clickhouse/index.ts, packages/app/src/ChartUtils.tsx, packages/app/src/EditChartForm.tsx, packages/app/src/api.ts
- use multi field selector for group by in event charts (we need to follow up w/ metrics, but that requires a new selector component)
- fixed a bug where multi-group-by requires same data type properties for events.
- fixed a bug where chart edit form will do excess re-rendering due to non-memo value passed into useDebounce
- fixed a regression where if a chart is in the error state, it'll be stuck with an error message even if the chart config changes to a valid one
=> Add multi-group-by support for event charts

.changeset/afraid-days-deny.md, .changeset/funny-singers-give.md, packages/api/src/clickhouse/index.ts, packages/app/src/ChartUtils.tsx
Fix the case when metric name is like 'ProcessedBytes_TCP_sum'
=> fix: query to extract metrics names + Summary count UI label

.changeset/loud-bottles-switch.md, docker/ingestor/Dockerfile
https://vector.dev/releases/0.40.0/
https://vector.dev/releases/0.40.1/
=> chore: bump vector to v0.40.1

packages/app/pages/benchmark.tsx, packages/app/pages/chart.tsx, packages/app/pages/dashboards/[dashboardId].tsx, packages/app/pages/dashboards/index.tsx, packages/app/pages/index.tsx, packages/app/pages/join-team.tsx, packages/app/pages/login/index.tsx, packages/app/pages/register.tsx, packages/app/pages/search/[savedSearchId].tsx, packages/app/pages/search/index.tsx, packages/app/pages/services.tsx, packages/app/pages/team/index.tsx, packages/app/src/emptyGetServerSideProps.tsx
Tested via:
1. Build
```sh
NODE_ENV=production NEXT_PUBLIC_IS_LOCAL_MODE=true npm run build
```
2. Run and observe configs are set correctly
```sh
HDX_LOCAL_DEFAULT_CONNECTIONS='[{"id":"local","name":"Demo","host":"https://demo-ch.hyperdx.io","username":"demo","password":"demo"}]' HDX_LOCAL_DEFAULT_SOURCES='[{"id":"l701179602","kind":"trace","name":"Demo Traces","connection":"local","from":{"databaseName":"default","tableName":"otel_traces"},"timestampValueExpression":"Timestamp","defaultTableSelectExpression":"Timestamp, ServiceName, StatusCode, round(Duration / 1e6), SpanName","serviceNameExpression":"ServiceName","eventAttributesExpression":"SpanAttributes","resourceAttributesExpression":"ResourceAttributes","traceIdExpression":"TraceId","spanIdExpression":"SpanId","implicitColumnExpres …
```
=> disable ASO to properly use publicRuntimeConfig

packages/app/src/clickhouse.ts, packages/app/src/components/DBRowTable.tsx, packages/app/src/hooks/useMetadata.tsx, packages/app/src/metadata.ts, packages/app/src/source.ts
We now use the `partition_key` in helping narrow down a given row that's selected in the UI, which is necessary for large datasets where the `partition_key` is not already part of the `primary_key`
Fixes HDX-1281
=> Use partition key in selecting search results

packages/app/src/DBSearchPage.tsx, packages/app/src/hooks/useExplainQuery.tsx
Utilizes the EXPLAIN ESTIMATE feature and queries CH to return # of rows that will be potentially read.
Ref: HDX-1136
Before:
After:
=> feat: Add # of planned read rows on search

packages/app/src/DBSearchPage.tsx, packages/app/src/components/DBRowTable.tsx
Adds an onError callback so that isLive is set to false when there is an error with the query.
Ref: HDX-1265
=> fix(results): Prevent live reloading if there's an error in results

packages/app/src/DBSearchPage.tsx
Adds effects to reset select and orderby field when connection sources are changed.
Ref: HDX-1176
[screen-capture.webm](https://github.com/user-attachments/assets/2c3a5316-0419-47bc-b6c9-395a0f72e1ca)
=> fix: When the data source is changed, ensure select/orderby fields are reset properly

packages/app/src/DBDashboardPage.tsx, packages/app/src/dashboard.ts
To prevent user data loss in case of a transient error in network/dashboard APIs, do not close the edit tile modal in case of error.
=> feat: Keep tile data if dashboard save failed

packages/app/package.json, packages/app/src/components/TimePicker/__tests__/utils.test.ts, packages/app/src/components/TimePicker/utils.ts, packages/app/src/timeQuery.ts, yarn.lock
When parsing a date with inferred parts, this commit changes the parser to assume that the intended date was in the past. This impacts individual date fields and date range fields.
=> fix: limit inferred dates to the past

.changeset/sharp-worms-impress.md, packages/api/src/controllers/alerts.ts, packages/api/src/controllers/dashboard.ts, packages/api/src/fixtures.ts, packages/api/src/routers/api/__tests__/dashboard.test.ts, packages/api/src/routers/api/dashboards.ts, packages/api/src/routers/external-api/v1/dashboards.ts, packages/app/src/DBDashboardPage.tsx, packages/app/src/DBSearchPageAlertModal.tsx, packages/app/src/components/Alerts.tsx, packages/app/src/components/DBEditTimeChartForm.tsx, packages/app/src/utils.ts, packages/app/src/utils/alerts.ts, packages/common-utils/src/types.ts
=> feat: UI for adding alerts for dashboard tiles

packages/app/src/components/TimePicker/__tests__/utils.test.ts
Some unit test cases were outside the scope of the describe block for `parseTimeRangeInput` tests. They were being executed outside the clock mocks, and this was only found on Jan 31st when the system clock was past the mock value.
=> fix(test): include all test cases inside describe context

packages/app/src/components/DBEditTimeChartForm.tsx
Fix broken query for fetching sample matched events for dashboard tiles caused by passing the `granularity` property to config.
=> fix: Sample matched events in charts

docker-compose.dev.yml
The OTEL collector can start execution before the Clickhouse DB is ready. This can cause the OTEL collector to crash, which aborts the container and caused the compose command to fail. This commit adds a health check to the Clickhouse container and then orders the OTEL collector container to wait until the database is healthy.
=> fix(dev): otel collector should wait for clickhouse

.changeset/gentle-coins-dress.md, packages/api/src/models/source.ts, packages/app/src/components/SourceForm.tsx, packages/app/src/source.ts, packages/common-utils/src/types.ts
Adds the ability to configure a gauge metric database source. Like logs and traces, it can infer the field configurations from a table if the column names match the otel collector schema.
Ref: HDX-1338
=> feat(metrics): Source support for gauge metrics

.changeset/dull-radios-wink.md, packages/app/src/TeamPage.tsx, packages/app/src/components/SourceForm.tsx, packages/app/src/config.ts
=> feat: introduce session table model form

.changeset/nervous-timers-dream.md, packages/api/src/routers/api/clickhouseProxy.ts, packages/app/src/ThemeWrapper.tsx, packages/app/src/api.ts, packages/app/src/components/ConnectionForm.tsx, packages/app/src/hooks/__tests__/useConnectionHealth.test.tsx, packages/app/src/hooks/useConnectionHealth.ts
1. Ensures errors from the ch proxy are properly returned 
2. Adds a connection check hook to periodically check connections and display a toast if connections are bad
3. Fixes the ConnectionForm to ensure that toast notifications are shown when test connections fail or when there's an error saving the form.
=> fix: Ensure errors from proxy are shown to the user

.changeset/metal-doors-burn.md, packages/api/src/models/source.ts, packages/app/src/components/SourceForm.tsx, packages/app/src/source.ts, packages/common-utils/src/types.ts
Updated the source configuration dialog for metrics to handle multiple, supported OTEL metric tables in a single form.
Ref: HDX-1390
=> feat(metrics): Support multiple OTEL tables

packages/app/src/TeamPage.tsx
Adds support for the user to add and view generic webhooks.
Ref: HDX-1396
=> feat: Add support for generic webhooks in Team page

.changeset/lemon-walls-collect.md, packages/app/src/TimelineChart.tsx, packages/app/src/components/DBRowSidePanel.tsx, packages/app/src/components/DBTracePanel.tsx, packages/app/src/components/DBTraceWaterfallChart.tsx, packages/common-utils/src/types.ts
- Add correlate span logs in traces waterfall chart
- `SeverityText: warn` will display as color yellow
- Some functions refactor
- Support both log tab and trace tab
Log Tab:
Trace Tab:
Ref: hdx-1181
=> feat: add correlate span logs in traces waterfall chart

packages/api/src/routers/api/sessions.ts, packages/app/src/DOMPlayer.tsx, packages/app/src/SessionSidePanel.tsx, packages/app/src/SessionSubpanel.tsx, packages/app/src/SessionsPage.tsx, packages/app/src/clickhouse.ts
1. Filter rrweb events by `ServiceName` (primary key)
2. Sort events by timestamp ASC
3. Add 4 hours offset to the original time range
=> fix+perf: filter rrweb events by service name and sort by timestamp

packages/app/src/SearchInputV2.tsx, packages/app/src/__tests__/utils.test.ts, packages/app/src/components/ContextSidePanel.tsx, packages/app/src/components/DBEditTimeChartForm.tsx, packages/app/src/components/SQLInlineEditor.tsx, packages/app/src/hooks/useFetchMetricResourceAttrs.tsx, packages/app/src/utils.ts
Adds backend call to grab attributes for a metric + adds them to autocomplete suggestions.
Ref: HDX-1402
=> feat: Add autocomplete of metrics attributes

packages/common-utils/src/__tests__/renderChartConfig.test.ts, packages/common-utils/src/renderChartConfig.ts, packages/common-utils/src/types.ts
Add query rendering support for CTEs and then using a CTE to support HyperDX v1 query logic to get sum metrics working in v2.
Ref: HDX-1337
=> feat: Support for sum metrics in charts

packages/app/src/DBDashboardPage.tsx, packages/app/src/__tests__/utils.test.ts, packages/app/src/components/DBEditTimeChartForm.tsx, packages/app/src/utils.ts
Uses existing functionality to grab correct metrics table based on metrics type and adds it to the from statement.
Ref: HDX-1418
=> fix: Ensure dashboard tiles use corresponding metric table

packages/common-utils/src/__tests__/renderChartConfig.test.ts, packages/common-utils/src/renderChartConfig.ts
Adds all available columns into the query so that we can properly apply the group by clause.
Ref: HDX-1419
=> fix: Ensure group-by works with sum metrics

.changeset/odd-hats-wash.md, packages/common-utils/src/__tests__/renderChartConfig.test.ts, packages/common-utils/src/clickhouse.ts, packages/common-utils/src/renderChartConfig.ts
Additional `renderChartConfig` support to transform a histogram select into the correct SQL syntax to generate a chart. For parity with v1, this query only handles quantile queries.
Ref: HDX-1339
=> feat: supporting quantile histogram metrics

packages/api/Dockerfile
- perf: copy root node_modules from builder stage to cut the deps size by half 
- fix: include `common-utils` node_modules for conflicts pkg like '@clickhouse/client'
=> fix: include common-utils node_modules (api dockerfile)

packages/app/src/DBDashboardPage.tsx
Without metric tables being passed to the chartconfig, the underlying query will not filter by metric name, which creates very large values in the charts as it uses all metrics.
Ref: HDX-1432
=> fix: Ensure chartConfigs have metric tables passed to them

packages/app/src/components/SourceForm.tsx
Add displayedTimestampValueExpression in source form, using `Timestamp` as default.
This field fix an issue where log and trace have different time column as primary key.
Ref: hdx-1438
=> feat: add displayedTimestampValueExpression

packages/app/src/components/ContextSidePanel.tsx
- Use empty `WHERE` query for surrounding context
https://github.com/user-attachments/assets/f6224dd4-cfd3-4082-94d0-14d9b39bf60c
Ref: hdx-1435
=> fix: surrounding context use original query

.changeset/forty-mails-deliver.md, packages/common-utils/src/renderChartConfig.ts
=> fix: handle 'filters' config (metrics)

packages/app/src/components/MetricNameSelect.tsx, packages/app/src/hooks/useMetadata.tsx, packages/common-utils/src/__tests__/metadata.test.ts, packages/common-utils/src/metadata.ts
The default max_rows_to_read clickhouse query setting was too low for the metrics table. Therefore, not enough rows were being scanned in order to fetch all possible metric names.
Ref: HDX-1451
=> fix: Ensure we read more rows in order to get all metric names

.changeset/famous-laws-laugh.md, packages/common-utils/src/__tests__/__snapshots__/renderChartConfig.test.ts.snap, packages/common-utils/src/renderChartConfig.ts
1. Eliminates a subquery select by pulling the handful of subquery fields up a level.
2. Removed `intDivOrZero` usage as this rounded fractional amounts to the nearest whole number, over/under stating the value.
3. Formatting of query now matches other queries.
Ref: HDX-1467
=> fix: few of histogram query fixes/tweaks

packages/common-utils/src/__tests__/__snapshots__/renderChartConfig.test.ts.snap, packages/common-utils/src/renderChartConfig.ts
WITH FILL messes with the heatmap bucketing logic, confusing the charting library. This change removes WITH FILL from query generation.
Ref: HDX-1456
=> fix: Remove fill from chart configs as it breaks heatmap and more

packages/app/src/DBSearchPage.tsx
When a saved search is saved, router was not maintaining any query params, including those such as "from" or "to", which caused the timeframe to reset back to "Live Tail". Added the current search params when routing to /search/{saved_search} after saving a search.
Ref: HDX-1393
=> Saved search time range fix

.changeset/quiet-dryers-taste.md, packages/api/.eslintrc.js, packages/api/tsconfig.test.json, packages/app/.eslintrc.js, packages/app/.stylelintignore, packages/app/Dockerfile, packages/app/src/components/DBEditTimeChartForm.tsx, packages/app/tsconfig.test.json, packages/common-utils/.eslintrc.js, packages/common-utils/tsconfig.json, packages/common-utils/tsconfig.test.json
1. Created separate tsconfig files for tests and prod code, including the test files in the test config.
2. Fixed linting error in DBEditTimeChartForm found while running local linting.
3. Excluded coverage CSS from the style lint task.
4. Updated app Dockerfile with test configuration and ran locally to ensure it was working.
Ref: HDX-1502
=> ci: fixes linting and release-local-ui target

.changeset/healthy-carpets-applaud.md, packages/app/src/components/DBDeltaChart.tsx, packages/common-utils/src/__tests__/__snapshots__/renderChartConfig.test.ts.snap, packages/common-utils/src/__tests__/renderChartConfig.test.ts, packages/common-utils/src/renderChartConfig.ts, packages/common-utils/src/types.ts
In order to easily use a CTE for fixing large index issues with delta
trace events, this commit updates the type and `renderWith` function to
render a nested chart config.
Ref: HDX-1343
---
Instead of sending 2 queries to the DB and enumerating all of parts
and offsets in the query, this change uses a CTE to select the parts.
This reduces the size of the HTTP request, which fixes the URI too
long response.
Ref: HDX-1343
=> fix: use CTE instead of listing all index parts in query

.changeset/gentle-lamps-drop.md, packages/api/src/controllers/team.ts, packages/api/src/routers/api/team.ts, packages/app/src/TeamPage.tsx, packages/app/src/api.ts
=> feat: Allow to update team name

packages/app/src/components/DBDeltaChart.tsx, packages/common-utils/src/renderChartConfig.ts, packages/common-utils/src/types.ts
Prior refactoring broke out the `sql` and `chartConfig` field names to allow each to be more strict in their types. The delta chart config call was missed in that refactoring.
After refactoring the schema:
After fixing the delta chart component:
In the UI:
Ref: HDX-1517
=> fix: update delta chart with clause

packages/app/src/ChartUtils.tsx, packages/app/src/components/DBTimeChart.tsx
Before:
After:
Also maintains coloring for SeverityText #695 established.
Ref: HDX-1523
=> fix: severity colors assigned only if data has name severitytextexpression

.changeset/popular-ants-ring.md, packages/common-utils/src/__tests__/metadata.test.ts, packages/common-utils/src/metadata.ts
In this example, the 'DESCRIBE' query should be fired twice only (for two different tables)
REF: HDX-1527
BEFORE:
AFTER:
=> perf: reuse existing queries promises to avoid duplicate requests

.changeset/strange-olives-rest.md, packages/app/src/components/DBRowSidePanel.tsx
=> fix: Session Replay tab not shown if no session source configured for trace

packages/app/src/__tests__/searchFilters.test.ts, packages/app/src/components/DBSearchPageFilters.tsx, packages/app/src/components/__tests__/DBSearchPageFilters.tsx, packages/app/src/searchFilters.tsx, packages/app/styles/SearchPage.module.scss
Adds
* NOT button next to the "Only" button that appears on hover of a search filter item. This will exclude the item from the search
* Search Filter filtering - restores filtering the search filter options by the text entered by the user
Enhances:
* Search filter ordering - selected items will appear on top, followed by an alphabetically ordered list of search filter items
***New NOT option***
Before
After
***Search filter ordering***
Before
After
***Searching within Filters***
=> fix: Improve search filter sorting, searching, and add exclude

.changeset/fast-phones-scream.md, packages/api/src/models/source.ts, packages/api/src/routers/api/clickhouseProxy.ts, packages/api/src/routers/api/logs.ts, packages/app/src/ChartUtils.tsx, packages/app/src/api.ts, packages/app/src/components/DBInfraPanel.tsx, packages/app/src/components/DBRowSidePanel.tsx, packages/app/src/components/DBTimeChart.tsx, packages/app/src/components/KubeComponents.tsx, packages/app/src/components/SourceForm.tsx, packages/common-utils/src/types.ts
1. users now should be able to go from k8s logs to metrics through 'Infrastructure' tab within details panel
2. introduce `convertV1ChartConfigToV2` to convert V1 multi-series chart config to V2 (only metrics)
Ref: HDX-1333, HDX-1536
=> feat: implement logs > metrics correlation flow

.changeset/neat-scissors-hope.md, packages/app/src/AppNav.tsx
Stores the collapse vs expand status of the side navigation in local storage so it's carried across browser windows/sessions.
Ref: HDX-1539
=> feat: retain side nav collapse/expand status between sessions

.changeset/light-emus-allow.md, packages/api/src/clickhouse/__tests__/__snapshots__/renderChartConfig.test.ts.snap, packages/api/src/clickhouse/__tests__/renderChartConfig.test.ts, packages/common-utils/src/__tests__/__snapshots__/renderChartConfig.test.ts.snap, packages/common-utils/src/renderChartConfig.ts
Add the ability to query a sum metric and obtain the underlying values instead of the rate of change between those points.
Ref: HDX-1543
=> feat: query sum metric without rate logic

.changeset/twenty-trains-turn.md, packages/app/src/ChartUtils.tsx, packages/app/src/KubernetesDashboardPage.tsx, packages/app/src/NamespaceDetailsSidePanel.tsx, packages/app/src/NodeDetailsSidePanel.tsx, packages/app/src/PodDetailsSidePanel.tsx, packages/app/src/hooks/useMetadata.tsx, packages/app/src/types.ts
Ref: HDX-1543 + HDX-1545
- fix: k8s dashboard uptime metrics 
- fix: warning k8s event body
- feat: add side panel to warning events table
- perf: opt pods/nodes/namespaces logs table performance
=> feat: introduce k8s preset dashboard - Pt2

.changeset/hip-dolls-reply.md, packages/app/src/HDXMultiSeriesTimeChart.tsx
Z-index on tooltip was causing it to show over an open drawer. Deleted it and just letting the default value ride.
Before:
After:
Ref: HDX-1540
=> fix: delete huge z-index for tooltip

packages/app/src/components/DBRowSidePanel.tsx
sessions can be up to 4 hours long so we need to search at least 4hr time frame.
=> expand session replay time range correctly for context panel

.changeset/clever-paws-rush.md, packages/app/src/AutocompleteInput.tsx, packages/app/src/components/InputLanguageSwitch.tsx
Look at the WHERE box, in particular the interaction between the `SQL | Lucene` block. It used to overlap with the input text, now it does not
https://github.com/user-attachments/assets/010a3f40-fd71-4414-b7ef-15786d7046a8
Fixes: HDX-1508
=> fix: select language width determined and passed to mantine component

packages/app/src/components/DBSearchPageFilters.tsx, packages/app/styles/SearchPage.module.scss
Fixes styles so that filter checkbox text can extend as the filter pane is resized.
Ref: HDX-1574
=> fix: Fix filter text cutoffs with resizable filter pane

.changeset/twelve-ladybugs-confess.md, Makefile, docker-compose.dev.yml, docker-compose.yml, docker/fullstack/Dockerfile, docker/fullstack/entry.sh, packages/api/.env.test, packages/api/src/config.ts, packages/api/src/tasks/index.ts, packages/app/src/config.ts
1. new env var RUN_SCHEDULED_TASKS_EXTERNALLY to opt out in-app task process
2. introduce new `prod-extended` build that includes mongodb process
3. GA k8s dashboard (only picking the connection)
4. bake check-alert task into fullstack app build
=> feat: introduce RUN_SCHEDULED_TASKS_EXTERNALLY

.changeset/spicy-windows-repeat.md, packages/app/src/components/ContextSidePanel.tsx
The originalWhere clause was never used in the surrounding context, there was just the tag displayed.
Fix: HDX-1570
=> fix: removed originalWhere from SurroundingContext tags

packages/app/src/TimelineChart.tsx, packages/app/src/components/DBTraceWaterfallChart.tsx, packages/app/styles/TimelineChart.module.scss
Utilizes resizable hook so that span names can be resized in timeline waterfall view.
[screen-capture (7).webm](https://github.com/user-attachments/assets/5b56e7fd-839d-434d-80f6-08fd3503a08a)
Ref: HDX-1534
=> feat: Resizable span name column in timeline chart

.changeset/honest-fishes-love.md, packages/app/package.json, packages/app/src/components/DBEditTimeChartForm.tsx, packages/app/src/hooks/__tests__/useChartConfig.test.tsx, packages/app/src/hooks/useChartConfig.tsx, packages/common-utils/src/types.ts
Ref: HDX-1607
Support ratio for both events and metrics charts
=> feat: compute charts ratio

packages/app/src/DBDashboardPage.tsx
=> feat: Dashboard auto-refresh

docker/otel-collector/config.yaml, smoke-tests/otel-collector/README.md, smoke-tests/otel-collector/data/auto-parse/default/assert_query.sql, smoke-tests/otel-collector/data/auto-parse/default/expected.snap, smoke-tests/otel-collector/data/auto-parse/default/input.json, smoke-tests/otel-collector/data/auto-parse/json-string/assert_query.sql, smoke-tests/otel-collector/data/auto-parse/json-string/expected.snap, smoke-tests/otel-collector/data/auto-parse/json-string/input.json, smoke-tests/otel-collector/data/auto-parse/otel-map/assert_query.sql, smoke-tests/otel-collector/data/auto-parse/otel-map/expected.snap, smoke-tests/otel-collector/data/auto-parse/otel-map/input.json, smoke-tests/otel-collector/hdx-1453-auto-parse-json.bats, smoke-tests/otel-collector/test_helpers/utilities.bash
Updates the OTEL pipeline to handle structured logs better. If the body content is an OTEL map, it will merge the body map into the log attributes map. If the body is a JSON object, it will parse the JSON string into an OTEL map, then merge the fields into the log attributes map.
Replacing the Body field doesn't work since the Clickhouse exporter schema defines Body as string, so any parsed out object ends up turning back into a string. At least as log resources, it's a lighter weight means of grouping and filtering in the UI.
Ref: HDX-1453
=> feat: Handle JSON-like structured logs better

.changeset/forty-ducks-invite.md, packages/api/src/routers/api/__tests__/sources.test.ts, packages/api/src/routers/api/__tests__/webhooks.test.ts
=> chore: adding test cases for additional routes

packages/app/src/SessionsPage.tsx
Address this issue:
> when I visit sessions page and select the source, the instruction shows up and I can see sessions once they are loaded. 
Improves loading state handling and checks for source type.
=> fix: Better loading state for Client Sessions page

packages/app/src/TeamPage.tsx, packages/app/src/components/Alerts.tsx
=> feat: Allow to add webhooks from Create Alert modal

.github/workflows/main.yml
Fixes
GitHub Actions has encountered an internal error when running your job integration.
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. 
For more details, see https://github.com/actions/runner-images/issues/11101
=> chore: Replace deprecated ubuntu runner

packages/app/src/LogTable.tsx, packages/app/styles/LogTable.module.scss
Allow to sort logs by timestamp in ASC direction.
https://github.com/user-attachments/assets/2782c35d-b1f8-40e9-8f07-b103e980d997
=> feat: Allow to sort logs by timestamp in ASC direction

packages/app/src/DBSearchPage.tsx, packages/app/src/components/DBRowTable.tsx, packages/app/src/components/DBSearchPageFilters.tsx, packages/app/src/components/PatternTable.tsx, packages/app/src/hooks/usePatterns.tsx, packages/app/src/hooks/useRowWhere.tsx
=> feat: denoise search results

.changeset/funny-crabs-whisper.md, packages/common-utils/src/clickhouse.ts
ref: HDX-1697
The response compression is only enabled on the browser side (regression: https://github.com/hyperdxio/hyperdx/commit/cfdd523516a1a3e39309a5de23828a30bb5b4b7f#diff-5b5bd864a2d51f72bb19df7630437c37e267b24de2a514fe486bd03653a09f32R458), which led to the fetch failed errors occasionally.
The root cause is still unclear. I'll file an issue in the SDK repo. Also we don't want an inconsistent behavior for the client settings anyway.
=> fix: 'Failed to fetch' errors

.changeset/long-goats-fail.md, packages/common-utils/src/clickhouse.ts
We should disable 'keep_alive' for the clickhouse browser client due to fetch API limit. Users would likely to hit the error in dashboard when there are many concurrent requests.
ref: HDX-1697
From https://fetch.spec.whatwg.org/
```
If contentLength is non-null and httpRequest’s [keepalive](https://fetch.spec.whatwg.org/#request-keepalive-flag) is true, then:
Let inflightKeepaliveBytes be 0.
Let group be httpRequest’s [client](https://fetch.spec.whatwg.org/#concept-request-client)’s [fetch group](https://fetch.spec.whatwg.org/#concept-fetch-group).
Let inflightRecords be the set of [fetch records](https://fetch.spec.whatwg.org/#concept-fetch-record) in group whose [request](https://fetch.spec.whatwg.org/#concept-fetch-record-request)’s …
```
=> fix: disable keep_alive on the browser side (ch client)

.changeset/few-mails-check.md, .changeset/twelve-dolls-yell.md, packages/api/src/tasks/__tests__/checkAlerts.test.ts, packages/api/src/tasks/checkAlerts.ts, packages/app/src/__tests__/utils.test.ts, packages/app/src/timeQuery.ts, packages/app/src/useFormatTime.tsx, packages/app/src/utils.ts, packages/common-utils/src/__tests__/utils.test.ts, packages/common-utils/src/renderChartConfig.ts, packages/common-utils/src/types.ts, packages/common-utils/src/utils.ts
Ref: HDX-1701
1. fix alerting time range filtering
2. add time range info to the alert body
=> fix: alerting time range filtering bug

package.json, packages/app/src/AppNav.tsx, packages/app/src/AuthPage.tsx, packages/app/src/TeamPage.tsx, packages/app/src/components/DBRowOverviewPanel.tsx, packages/app/src/components/DBTracePanel.tsx, packages/app/src/source.ts, packages/common-utils/src/types.ts
- add top level attributes to overview panel: HDX-1715
- add connection name to sources list
- introduce additional default aliases for otel (service, level, duration)
- fix bug with being unable to save source after deselecting correlated log source
- copy improvements
- `dev:down` npm command to tear down dev docker compose
=> feat: misc improvements

smoke-tests/otel-collector/hdx-1453-auto-parse-json.bats, smoke-tests/otel-collector/hdx-1514-inference.bats, smoke-tests/otel-collector/test_helpers/utilities.bash
1. The wait_for_ready function does not need the endpoint param. We should remove it to make maintenance easier.
2. The hdx-1514-inference test should use the attempt_env_cleanup function to pick up the logic that skips container tear down.
Ref: HDX-1730
=> refactor: clean up cruft from test suite

docker/otel-collector/Dockerfile
Pulling the image from ghcr creates more friction for users, especially when dealing with issues like expired tokens. For example, you might see errors such as
```
docker pull ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor:0.126.0
Error response from daemon: Head "https://ghcr.io/v2/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-opampsupervisor/manifests/0.126.0": denied: denied
```
=> DX: pull opampsupervisor base image from dockerhub

packages/app/package.json, packages/app/src/components/DBTraceWaterfallChart.tsx
HDX-1772
- if `implicitColumnExpression` had a `Map` column type in it, we'd try to render objects that crashed the trace panel, switching logs to always render off of body expression first. Just to be defensive, we also try to stringify the Body before displaying
HDX-1769
- If root/parent spans were missing, their children spans did not render properly, we were incorrectly assuming logs with a spanId were a valid parent span which meant we did not properly render orphaned spans.
bonus: Fixes NX cache misconfiguration which should stop Vercel deployment errors due to cache
=> fix: trace panel crashes/missing spans due to misconfig/missing data

.changeset/empty-balloons-sin.md, packages/app/src/ChartUtils.tsx, packages/app/src/DBSearchPage.tsx
Adds a groupby for traces based on statusCodeExpression akin to severityTextExpression for logs. Colors based on message
=> fix: colors display for traces

docker/otel-collector/supervisor_docker.yaml
Adds environment variable to allow for passthrough_logs to be enabled in the supervisor config
Test locally with:
Edit docker-compose.dev.yaml
Add `OTEL_SUPERVISOR_PASSTHROUGH_LOGS: 'true'` under the otel environment variables
```
make dev-up
```
Ref: HDX-1859
=> chore: Make passthrough_logs an envvar controlled setting in collector

.changeset/cold-planets-report.md, packages/app/src/components/OnboardingModal.tsx
Fixes HDX-1835
I tested this by running the main branch first via `cd packages/app && yarn dev:local`, loading localhost:8080 and clicked demo servers, pasting the json from the HDX-1835 linear ticket into the `hdx-local-source` localStorage slot, verified some sources gave that permissions issue, then closed the tab. Then I checked out this branch, opened a new tab with localhost:8080, selected demo servers, and all demo sources work as expected
=> fix: fix play.hyperdx.io for those with stale demo instances

.github/workflows/release.yml, Makefile
Ref: HDX-1976
1. Updated release-xxx commands to prevent image tag overrides
2. Updated release workflow so that notify-xxx steps won't be triggered if no new app image was pushed
=> ci: update release scripts to prevent tag overrides

packages/app/src/components/SQLInlineEditor.tsx
Cleans up these errors from the console
=> fix: set value to emptystring when undefined

.changeset/itchy-walls-smoke.md, packages/app/src/components/DBRowTable.tsx, packages/app/src/useFormatTime.tsx, packages/common-utils/src/utils.ts
=> feat: Add verbose time range used for search in results table

.changeset/little-parents-rescue.md, packages/common-utils/src/__tests__/__snapshots__/renderChartConfig.test.ts.snap, packages/common-utils/src/renderChartConfig.ts
=> fix: Ensure percentile aggregations on histograms dont create invalid SQL queries due to improperly escaped aliases.

.changeset/strong-zoos-ring.md, packages/api/package.json, packages/app/package.json, packages/common-utils/package.json
Closes HDX-2031
This node version is already used as the docker image version, so I'm not expecting anything to break. Tested dev and all-in-one image
=> chore: bump node version

.changeset/blue-months-switch.md, packages/api/src/controllers/team.ts, packages/api/src/models/team.ts, packages/api/src/routers/api/team.ts, packages/app/src/TeamPage.tsx, packages/app/src/api.ts, packages/app/src/config.ts, packages/app/src/hooks/useMetadata.tsx
Closes HDX-2068
Allows a team to disable fetching field metadata across the app. Fetching is enabled by default. Here's the setting:
And here's what it looks like when the setting is disabled:
Notice that autocomplete is doing nothing and filters are not loaded
=> feat: team setting to disable fetching field metadata

.changeset/forty-rabbits-share.md, packages/api/src/controllers/team.ts, packages/api/src/models/team.ts, packages/api/src/routers/api/team.ts, packages/app/src/TeamPage.tsx, packages/app/src/api.ts, packages/app/src/hooks/useMetadata.tsx, packages/common-utils/src/metadata.ts
1. Merge all clickhouse client setting related endpoints into one `/clickhouse-settings` plus controllers
2. Add tooltips to the setting UIs
3. Introduce `metadataMaxRowsToRead` setting for tweaking metadata query perf
Ref: HDX-2075
Related: HDX-2023
=> feat: introduce team 'clickhouse-settings' endpoint + `metadataMaxRowsToRead` setting

.changeset/fast-jeans-cough.md, packages/app/src/KubernetesDashboardPage.tsx, packages/app/src/components/KubeComponents.tsx
Fix the regression due to otel collector version bump. 
The k8s event object should sit within the `LogAttributes` field instead of `Body` field
Ref: HDX-2158
=> fix: k8s event property mappings

.changeset/happy-tips-cough.md, docker/otel-collector/Dockerfile, docker/otel-collector/entrypoint.sh, docker/otel-collector/supervisor_docker.yaml.tmpl, packages/api/src/opamp/controllers/opampController.ts
plus fixing startup issue when the team isn't created yet
=> fix: handle the case when `CUSTOM_OTELCOL_CONFIG_FILE` is not specified

.changeset/quiet-socks-cry.md, packages/api/src/tasks/__tests__/checkAlerts.test.ts, packages/api/src/tasks/__tests__/singleInvocationAlert.test.ts, packages/api/src/tasks/template.ts
Uses the title from the alerting tile instead of the first tile on a dashboard.
Ref: HDX-2270
=> fix: use correct title in alert on dashboards

packages/api/src/models/team.ts, packages/api/src/routers/api/__tests__/team.test.ts
Needed in the upstream fork and putting it here will make the merges easier long term.
=> refactor: expose virtual `id` field on the `ITeam` interface

.changeset/stale-brooms-sparkle.md, packages/app/src/components/DBRowTable.tsx, packages/app/src/hooks/useOffsetPaginatedQuery.tsx
=> feat: Improve search speed by chunking long time range searches into smaller incremental search windows.

.changeset/violet-kiwis-cover.md, packages/app/src/components/SourceForm.tsx, packages/app/src/sessions.ts, packages/app/src/source.ts, packages/common-utils/src/types.ts
Closes HDX-1678
This PR removes the Timestamp Column, Log Attributes Expression, Resource Attributes Expression, and Implicit Column Expression when editing or creating a Session-kind source. Default values are used for these fields when querying a Session-kind source.
To allow creating a source without resourceAttributesExpression, eventAttributesExpression, timestampValueExpression, or implicitColumnExpression, the SessionSourceAugmentation schema was updated, which resulted in an update to the `TSource` type. To prevent a cascade of changes throughout the app due to `timestampValueExpression` now being optional on `TSource`, the `useSource` and `useSources` queries were updated to set default `timestampValueExpression` for session-kind sources.
This PR also adds validation (similar to …
=> feat: remove useless session source fields

.changeset/sweet-boats-study.md, packages/api/src/controllers/user.ts, packages/api/src/routers/api/team.ts
Closes HDX-2188
This PR updates the user deletion functionality so that Alerts that were created by the deleted user are updated with a new `createdBy` value referencing the user that is doing the deleting.
Alert was created by `test1234@clickhouse.com`:
`drew.davis@clickhouse.com` deletes `test1234@clickhouse.com`:
The Alert now shows createdBy `drew.davis@clickhouse.com`:
=> fix: Update Alerts when creating user is deleted

.changeset/smooth-schools-ring.md, packages/app/src/components/DBRowTable.tsx, packages/app/src/hooks/__tests__/useOffsetPaginatedQuery.test.tsx, packages/app/src/hooks/useOffsetPaginatedQuery.tsx, packages/common-utils/src/__tests__/utils.test.ts, packages/common-utils/src/utils.ts
Closes HDX-2407
This PR fixes searches which sort in ascending time order or do not order based on time. With this change, time-based "chunking" of queries (#1125) will only be used when the results are ordered by time. Further, when ordering by time _ascending_, the chunks will load in ascending time order (rather than descending time order).
=> fix: Fix ascending order in windowed searches

.changeset/shiny-pugs-shave.md, packages/api/src/tasks/__tests__/checkAlerts.test.ts, packages/api/src/tasks/__tests__/checkAlertsTask.test.ts, packages/api/src/tasks/__tests__/singleInvocationAlert.test.ts, packages/api/src/tasks/checkAlerts.ts, packages/api/src/tasks/providers/__tests__/index.test.ts, packages/api/src/tasks/providers/default.ts, packages/api/src/tasks/providers/index.ts, packages/api/src/tasks/template.ts, packages/api/src/tasks/types.ts
Closes HDX-2281
This PR adds two additional functions to the `AlertProvider` interface, and implements them for the default provider. The intention behind these changes is to eliminate all direct Mongo access from the alert check loop, and instead handle the connection to Mongo through the `AlertProvider` interface.
The new functions are as follows:
1. `getWebhooks(teamId): Map<string, IWebhook>`: This function is used to retrieve the webhooks that may be used to send alerts. While it would be nice to just attach the webhook information to the AlertDetails, we have (unfinished?) support for referencing arbitrary wehbooks within message templates, and this pattern better supports that future use-case without having to process message templates while loading alerts.
3. …
=> refactor: Decouple alerts processing from Mongo

.changeset/selfish-goats-collect.md, packages/api/src/tasks/__tests__/checkAlertsTask.test.ts, packages/api/src/tasks/checkAlerts.ts, packages/api/src/tasks/providers/__tests__/index.test.ts, packages/api/src/tasks/providers/default.ts, packages/api/src/tasks/providers/index.ts
HDX-2078
This PR shifts the creation of the ClickHouse client used by alerts to the AlertProvider interface, to support other auth methods in other AlertProvider implementations.
Running locally, the default provider creates the client and successfully queries with it:
=> feat: Get ClickHouse client from AlertProvider

.changeset/strange-eagles-roll.md, packages/app/src/DBSearchPage.tsx, packages/app/src/components/DBEditTimeChartForm.tsx, packages/app/src/components/DBTableSelect.tsx, packages/app/src/components/SourceSchemaPreview.tsx
Closes HDX-2404
This PR adds a new info icon next to various Source pickers, which when clicked opens a modal that shows the schema(s) for the table(s) associated with the source.
<details>
<summary>On the search page</summary>
</details>
<details>
<summary>In the source form</summary>
</details>
<details>
<summary>In the chart explorer</summary>
</details>
<details>
<summary>Multiple schemas are shown when a metric source is chosen</summary>
</details>
=> feat: Add source schema previews

.changeset/cuddly-toys-cheat.md, packages/app/src/components/SourceSchemaPreview.tsx
This PR updates the icon used to show a sources SQL schema, based on team feedback. The new icon matches the icon used to show search SQL.
=> style: Update icon used to show source schema

.changeset/early-items-design.md, packages/app/src/hooks/__tests__/useAutoCompleteOptions.test.tsx, packages/app/src/hooks/useAutoCompleteOptions.tsx, packages/app/src/hooks/useMetadata.tsx, packages/common-utils/src/metadata.ts
This reverts commit d60d92030dfa4473e0f7ea4f75178d1bc104af8b.
Commit breaks dashboards with:
=> Revert "fix: json getKeyValues (useful for autocomplete) (#1186)"

.changeset/little-games-change.md, packages/common-utils/src/metadata.ts
To pull things like metric tags, `getKeyValues` method should fallback to the query w/o using CTE for better performance
Ref: HDX-2482
=> perf: disable CTE if disableRowLimit flag is true (getKeyValues method)

.changeset/thirty-seahorses-relax.md, packages/api/src/tasks/providers/default.ts, packages/common-utils/src/clickhouse/browser.ts, packages/common-utils/src/clickhouse/index.ts, packages/common-utils/src/clickhouse/node.ts
Closes HDX-2481
For browser-based queries, the clickhouse requests go through the clickhouse-proxy endpoint, which re-writes the user-agent header for analytics purposes.
Alerts queries don't go through the clickhouse-proxy, and clickhouse-js doesn't allow us to directly set the user-agent header. We can instead provide an `application` name, which is pre-pended to the default clickhouse-js user-agent, yielding a user-agent like:
```
hyperdx-alerts 2.5.0 clickhouse-js/1.12.1 (lv:nodejs/v22.19.0; os:darwin)
```
The user agent shows up in ClickHouse query logs:
=> feat: Add user-agent to alerts client

.changeset/itchy-peas-pull.md, packages/app/src/DBSearchPage.tsx, packages/app/src/DashboardFiltersEditModal.tsx, packages/app/src/components/DBEditTimeChartForm.tsx, packages/app/src/components/DBTableSelect.tsx, packages/app/src/components/SourceSchemaPreview.tsx, packages/app/src/components/SourceSelect.tsx, packages/app/styles/SourceSelectControlled.module.scss
This PR enhances the `SourceSchemaPreview` button integration in `SourceSelect` and `DBTableSelect` components.
=> feat: enhance SourceSchemaPreview button integration in select components
